### ISSUE TITLE
check error in bin_refinement (metawrap ver. 1.1.1)

### ISSUE THREAD

**Issue by yyuangy** [bxlab/metaWRAP#113]
When I do the bin_refinement, the step of "checkm -tree" was forcibly stopped with the following error message:
_Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/home/ohta/miniconda2/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/home/ohta/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/home/ohta/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 110, in tree
    binFiles = self.binFiles(options.bin_folder, options.extension)
  File "/home/ohta/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 87, in binFiles
    all_files = os.listdir(binFolder)
OSError: [Errno 20] Not a directory: 'binsA.stats'_

Could you help me to solve this problem?

**Comment by yyuangy** [comment]
Thank you very much for your quick reply! I sent you the text file of metawrap output by email.

**Comment by ursky** [comment]
I did not get anything. Just attach it here in github so everyone can have a look.

**Comment by yyuangy** [comment]
[nohup.out.zip](https://github.com/bxlab/metaWRAP/files/2815650/nohup.out.zip)
Ok, please check it! Thank you very much!

**Comment by ursky** [comment]
Looks like there was an error caused by files in the output directory from a previous run. In particular, metawrap thought that binsA.stats (which was already present in the output directory at the time of this run) was a directory with bins... Re-run with a clear output folder, and you should be fine. I added a fail-safe to prevent this in `metawrap v1.1.3`, when it comes out.

**Comment by yyuangy** [comment]
Thank you very much! I will try this again and report the result later.
