### ISSUE TITLE
Error running metawrap bin_refinement in docker container

### ISSUE THREAD

**Issue by mb1069** [bxlab/metaWRAP#123]
Hi, I'm getting the following error when running metawrap bin_refinement through the docker container, is this due to the checkM data being absent?
```
Traceback (most recent call last):
  File "/usr/local/bin/metawrap-scripts/fix_config_naming.py", line 4, in <module>
    for line in open(sys.argv[1]):
IOError: [Errno 2] No such file or directory: '/Ilhodj/binsB/*'
mv: can't rename '/Ilhodj/tmp.fa': No such file or directory
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  [Warning] Skipping bin unbinned.fa as it has a size of 0 bytes.
  Identifying marker genes in 2 bins with 1 threads:
    Finished processing 0 of 2 (0.00%) bins.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'

  Saving HMM info to file.

  Calculating genome statistics for 2 bins with 1 threads:
    Finished processing 0 of 2 (0.00%) bins.
    Finished processing 1 of 2 (50.00%) bins.
    Finished processing 2 of 2 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 711, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 1252, in parseOptions
    self.tree(options)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 157, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/usr/local/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 105, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/usr/local/lib/python2.7/site-packages/checkm/resultsParser.py", line 85, in parseBinHits
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

real	0m1.857s
user	0m1.180s
sys	0m0.240s
```

**Comment by ursky** [comment]
No, i think the problem happens before CheckM. This is the line that fails:
```
for f in ${out}/binsB/*; do 
    ${SOFT}/fix_config_naming.py $f > ${out}/tmp.fa; mv ${out}/tmp.fa $f
done
```

Can you have a look a the `/Ilhodj/binsB/` directory? Maybe its empty. Also, can you give the stdout of metawrap as well?

**Comment by mb1069** [comment]
Might be more than one problem, I removed all the arguments for binsB from the input, and am now getting
```
------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
You do not seem to have permission to edit the checkm config file
located at /usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG'
Sorry, CheckM cannot run without a valid data folder.

Unexpected error: <type 'exceptions.TypeError'>
```

**Comment by ursky** [comment]
Did you configure the CheckM database before running, as per instructions? Looks like you might have to do that with `sudo`.

**Comment by mb1069** [comment]
Do you mean this? https://github.com/bxlab/metaWRAP/blob/master/installation/database_installation.md

**Comment by ursky** [comment]
Yes, but specifically running the `checkm data setRoot` command.

**Comment by mb1069** [comment]
It's not playing nicely with CWL (which is calling the docker container). However, I've managed to extend the docker container to fetch and setup the checkM db successfully

**Comment by ursky** [comment]
Interesting. Do you mind posting some instruction of what you did for others using Docker?

**Comment by mb1069** [comment]
```
FROM quay.io/biocontainers/metawrap:1.1--0
RUN echo -e "cat << EOF\n/db/CheckM\nEOF\n" | checkm data setRoot

RUN curl -o checkm.tar.gz https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_2015_01_16.tar.gz
RUN zcat checkm.tar.gz | tar -xvf - -C /db/CheckM/ && rm *.gz
```
Not overly fond of the zcat trick but busybox doesn't seem to include a full version of tar
