### ISSUE TITLE
CheckM bin_refinement Not a Directory error in Docker

### ISSUE THREAD

**Issue by mb1069** [bxlab/metaWRAP#125]
Hi, I'm running into an issue when using the bin_refinement tool with 3 directory inputs;
```
------------------------------------------------------------------------------------------------------------------------
-----                                        Running CheckM on bin.0.fa bins                                       -----
------------------------------------------------------------------------------------------------------------------------

/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************


Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 711, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 1252, in parseOptions
    self.tree(options)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 110, in tree
    binFiles = self.binFiles(options.bin_folder, options.extension)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 87, in binFiles
    all_files = os.listdir(binFolder)
OSError: [Errno 20] Not a directory: 'bin.0.fa'
```
Any idea how I could resolve this?

**Comment by ursky** [comment]
It would be helpful to see the entire output for context.

**Comment by mb1069** [comment]
```docker \
    run \
    -i \
    --volume=/private/tmp/docker_tmpog2toc7o:/IDNxfv:rw \
    --volume=/private/var/folders/ws/cf5jmmns74qb8cj5pmhvs_gjl5jrp6/T/yj_s56n8:/tmp:rw \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins:/var/lib/cwl/stg87bd859f-de83-4c99-837b-7de41bbdf010/concoct_bins:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/maxbin2_bins:/var/lib/cwl/stgbd3c6577-fe55-4753-958d-2a6e17fb7e59/maxbin2_bins:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/metabat2_bins:/var/lib/cwl/stgb8239c25-0b1b-45b3-8de7-c828986cb3e6/metabat2_bins:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.40.fa:/IDNxfv/bin.40.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.11.fa:/IDNxfv/bin.11.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.25.fa:/IDNxfv/bin.25.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.35.fa:/IDNxfv/bin.35.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.5.fa:/IDNxfv/bin.5.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.21.fa:/IDNxfv/bin.21.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.15.fa:/IDNxfv/bin.15.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.44.fa:/IDNxfv/bin.44.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.31.fa:/IDNxfv/bin.31.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.1.fa:/IDNxfv/bin.1.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.20.fa:/IDNxfv/bin.20.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.14.fa:/IDNxfv/bin.14.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.45.fa:/IDNxfv/bin.45.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.30.fa:/IDNxfv/bin.30.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.0.fa:/IDNxfv/bin.0.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.41.fa:/IDNxfv/bin.41.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.10.fa:/IDNxfv/bin.10.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.24.fa:/IDNxfv/bin.24.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.34.fa:/IDNxfv/bin.34.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.4.fa:/IDNxfv/bin.4.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.29.fa:/IDNxfv/bin.29.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.9.fa:/IDNxfv/bin.9.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.39.fa:/IDNxfv/bin.39.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.19.fa:/IDNxfv/bin.19.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.48.fa:/IDNxfv/bin.48.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.18.fa:/IDNxfv/bin.18.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.28.fa:/IDNxfv/bin.28.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.8.fa:/IDNxfv/bin.8.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.38.fa:/IDNxfv/bin.38.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.23.fa:/IDNxfv/bin.23.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.46.fa:/IDNxfv/bin.46.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.17.fa:/IDNxfv/bin.17.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.33.fa:/IDNxfv/bin.33.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.3.fa:/IDNxfv/bin.3.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.13.fa:/IDNxfv/bin.13.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.42.fa:/IDNxfv/bin.42.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.27.fa:/IDNxfv/bin.27.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.37.fa:/IDNxfv/bin.37.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.7.fa:/IDNxfv/bin.7.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.12.fa:/IDNxfv/bin.12.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.43.fa:/IDNxfv/bin.43.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.26.fa:/IDNxfv/bin.26.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.36.fa:/IDNxfv/bin.36.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/unbinned.fa:/IDNxfv/unbinned.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.6.fa:/IDNxfv/bin.6.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.22.fa:/IDNxfv/bin.22.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.47.fa:/IDNxfv/bin.47.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.16.fa:/IDNxfv/bin.16.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.32.fa:/IDNxfv/bin.32.fa:ro \
    --volume=/Users/mdb/work/binning_workflow/test_data/tools/metawrap_bin_refinement/concoct_bins/bin.2.fa:/IDNxfv/bin.2.fa:ro \
    --workdir=/IDNxfv \
    --read-only=true \
    --user=1717101254:384566875 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/IDNxfv \
    --cidfile=/var/folders/ws/cf5jmmns74qb8cj5pmhvs_gjl5jrp6/T/tmpp3evf2pw/20190214174005-613540.cid \
    metawrap_w_checkm:latest \
    metawrap \
    bin_refinement \
    -o \
    /IDNxfv \
    -m \
    1024 \
    -t \
    1 \
    -c \
    50 \
    -x \
    5 \
    -A \
    /var/lib/cwl/stg87bd859f-de83-4c99-837b-7de41bbdf010/concoct_bins \
    -B \
    /var/lib/cwl/stgbd3c6577-fe55-4753-958d-2a6e17fb7e59/maxbin2_bins \
    -C \
    /var/lib/cwl/stgb8239c25-0b1b-45b3-8de7-c828986cb3e6/metabat2_bins
metawrap bin_refinement -o /IDNxfv -m 1024 -t 1 -c 50 -x 5 -A /var/lib/cwl/stg87bd859f-de83-4c99-837b-7de41bbdf010/concoct_bins -B /var/lib/cwl/stgbd3c6577-fe55-4753-958d-2a6e17fb7e59/maxbin2_bins -C /var/lib/cwl/stgb8239c25-0b1b-45b3-8de7-c828986cb3e6/metabat2_bins

------------------------------------------------------------------------------------------------------------------------
-----           There is 1024 RAM and 1 threads available, and each pplacer thread uses >40GB, so I will           -----
-----                                          use 1 threads for pplacer                                           -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                                BEGIN PIPELINE!                                               #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                              setting up output folder and copything over bins...                             -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****            Warning: /IDNxfv already exists. It is HIGHLY recommended that you clear this directory           *****
*****                               to prevent any conflicts... Attempting to clean.                               *****
************************************************************************************************************************

rm: can't remove '/IDNxfv/binsA': No such file or directory
rm: can't remove '/IDNxfv/binsB': No such file or directory
rm: can't remove '/IDNxfv/binsC': No such file or directory
rm: can't remove '/IDNxfv/binsAB': No such file or directory
rm: can't remove '/IDNxfv/binsBC': No such file or directory
rm: can't remove '/IDNxfv/binsAC': No such file or directory
rm: can't remove '/IDNxfv/binsABC': No such file or directory

------------------------------------------------------------------------------------------------------------------------
-----                                          there are 50 bins in binsA                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                           there are 2 bins in binsB                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                           there are 2 bins in binsC                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                             There are 3 bin sets!                                            -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                              Fix contig naming by removing special characters...                             -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                             BEGIN BIN REFINEMENT                                             #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----              There are three bin folders, so there 4 ways we can refine the bins (A+B, B+C, A+C,             -----
-----                                    A+B+C). Will try all four in parallel!                                    -----
------------------------------------------------------------------------------------------------------------------------

Specified 2 input bin sets: -1 binsC -2 binsB
Add folder/bin name to contig name for binsC bins
Add folder/bin name to contig name for binsB bins
Combine all bins together
The number of refined bins: 2
Exporting refined bins...
Extracting refined bin: Refined_2.fasta
Deleting temporary files

All done!
Specified 2 input bin sets: -1 binsA -2 binsC
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsC bins
Combine all bins together
The number of refined bins: 1
Exporting refined bins...
Extracting refined bin: Refined_1.fasta
Deleting temporary files

All done!
Specified 2 input bin sets: -1 binsA -2 binsB
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsB bins
Combine all bins together
The number of refined bins: 2
Exporting refined bins...
Extracting refined bin: Refined_2.fasta
Deleting temporary files

All done!
Specified 3 input bin sets: -1 binsA -2 binsB -3 binsC
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsB bins
Add folder/bin name to contig name for binsC bins
Combine all bins together
The number of refined bins: 2
Exporting refined bins...
Extracting refined bin: Refined_2.fasta
Deleting temporary files

All done!

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 2 refined bins in binsAB                                      -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 2 refined bins in binsBC                                      -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 1 refined bins in binsAC                                      -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 2 refined bins in binsABC                                     -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                     Bin refinement finished successfully!                                    -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                            fixing bin naming to .fa convention for consistancy...                            -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                      RUNNING CHECKM ON ALL SETS OF BINS                                      #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                        Running CheckM on bin.0.fa bins                                       -----
------------------------------------------------------------------------------------------------------------------------

/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************


Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 711, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 1252, in parseOptions
    self.tree(options)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 110, in tree
    binFiles = self.binFiles(options.bin_folder, options.extension)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 87, in binFiles
    all_files = os.listdir(binFolder)
OSError: [Errno 20] Not a directory: 'bin.0.fa'

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
***************************************************************************************************************```

**Comment by ursky** [comment]
I am not sure what is going on, but I think it might stem from you using the same output folder. Can you try to delete the output Dir, and retry? If it still doesn't work, can you give the contents of the output folder after it quits?

**Comment by mb1069** [comment]
Well spotted, I set the output folder to a different directory to the input and it's progressing. Running it on a high mem machine now to get past the next hurdle.

**Comment by ursky** [comment]
Leaving open for visibility.
