### ISSUE TITLE
bin refinement error

### ISSUE THREAD

**Issue by raw937** [bxlab/metaWRAP#129]
Hello, 

I have had an error at the bin refinement step. 
module load miniconda3
source activate /opt/apps/conda/envs/metawrap/

metawrap bin_refinement -o refinement/U_refine -t 28 -A U_metawrap/metabat2_bins -B U_metawrap/maxbin2_bins/ -C U_metawrap/concoct_bins/ -c 80 -x 10

It appears to be a python 2.7 error with checkm. I have installed checkm locally as well no problem. 

#errors
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 236 bins with 28 threads:
Process Process-2:ssing 0 of 236 (0.00%) bins.
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-13:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-14:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-7:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-25:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-28:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-5:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-12:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-4:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-9:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-24:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-6:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-11:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-23:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-17:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-19:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-8:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-18:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-20:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-27:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-21:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-16:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-22:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-26:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-29:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-3:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-10:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'
Process Process-15:
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hmms/phylo.hmm'

Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-2DEzAV/.nfs00000000000cf8710009ef64'
  Saving HMM info to file.

  Calculating genome statistics for 236 bins with 28 threads:
    Finis
    Finished processing 33 of 236 (13.98%) bins.
    Finished processing 50 of 236 (20.76%) bins.
    Finished processing 66 of 236 (27.97%) bins.
    Finished processing 83 of 236 (35.17%) bins.
    Finished processing 100 o 236 (41.95%) bins.
    Finished processing 116 of 236 (49.15%) bins.
    Finishe
    Finished processing 149 of 236 (62.71%) bins.
    Finished processing 165 of 236 (69.92%) bins.
    Finis
    Finished processing 197 of 236 (83.47%) bins.
    Finished processing 214 of 236 (90.68%) bins.
    Fin
    Finished processing 236 of 236 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.
Traceback (most recent call last):
  File "/opt/apps/conda/envs/metawrap/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 105, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/opt/apps/conda/envs/metawrap/lib/python2.7/site-packages/checkm/resultsParser.py", line 85, in parseBinHits
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

real	53m56.890s
user	156m20.459s
sys	4m5.759s

**Comment by ursky** [comment]
The error appears to be coming from the checkm database not being installed correctly - note the `No such file or directory: 'hmms/phylo.hmm'` warning. Its possible you configured the database with the wrong checkm (the locally installed one)? Either fix that, or alternatively you can just place your working checkm in a higher priority within `$PATH` so it is used instead of the conda one.
