### ISSUE TITLE
checkM failure in metawrap conda env

### ISSUE THREAD

**Issue by ilyavs** [bxlab/metaWRAP#137]
Hello,
I used metawrap in the past with no issues. However, now I ran it and checkM failed. After a number of re-installation attempts, I still can't get checkM to work on the test data when I run it in the metawrap conda env. However, when I run it in an environment that only has checkM installed, it works.
The error I get now with checkM in the metawrap environment is:
Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_2.7/bin/checkm", line 711, in <module>
    checkmParser.parseOptions(args)
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_2.7/lib/python2.7/site-packages/checkm/main.py", line 1252, in parseOptions
    self.tree(options)
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_2.7/lib/python2.7/site-packages/checkm/main.py", line 157, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_2.7/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 105, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_2.7/lib/python2.7/site-packages/checkm/resultsParser.py", line 85, in parseBinHits
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Any ideas on how to fix it?
Thanks,
Ilya.

**Comment by ilyavs** [comment]
Resolved by  downgrading checkM to version 1.0.12

**Comment by ursky** [comment]
Thanks for the bu report. This is good info. I will enforce CheckM v1.0.12 in the next version of metaWRAP (v1.1.5), when it comes out.

**Comment by ilyavs** [comment]
I did multiple changes and didn't keep track. I would suggest some testing of a fresh install to verify which dependencies to enforce.
Best,
Ilya.

**Comment by rotoscan** [comment]
@ilyavs 
Hello Ilya,

how did you do to downgrade the metawrap version?

Simply, once the conda environment was loaded, you did $ conda install metawrap-mg=1.x.x, where x was the desired downgraded version?

Thanks!!

Best,
Rodolfo

**Comment by ilyavs** [comment]
@rotoscan I don't remember by now but I think you are correct.

**Comment by ursky** [comment]
After re-reading this issue, I suppose I should enforce checkm-genome=1.0.12 in the metaWRAP v1.2 thats about to come out, just in case. I am trying to streamline the dependencies in v1.1.8, so if you find more issues, let me know.
