### ISSUE TITLE
plot binning results fails

### ISSUE THREAD

**Issue by ilyavs** [bxlab/metaWRAP#138]
Hi,
It seems like plot binning results uses a removed feature of matplotlib. I got the following error:
Traceback (most recent call last):
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_2.7/bin/metawrap-scripts/plot_binning_results.py", line 69, in <module>
    ax.set_axis_bgcolor("white")
AttributeError: 'AxesSubplot' object has no attribute 'set_axis_bgcolor'
mv: cannot stat \u2018binning_results.eps\u2019: No such file or directory
mv: cannot stat \u2018binning_results.png\u2019: No such file or directory
Traceback (most recent call last):
  File "/net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_2.7/bin/metawrap-scripts/plot_binning_results.py", line 69, in <module>
    ax.set_axis_bgcolor("white")
AttributeError: 'AxesSubplot' object has no attribute 'set_axis_bgcolor'
mv: cannot stat \u2018binning_results.eps\u2019: No such file or directory
mv: cannot stat \u2018binning_results.png\u2019: No such file or directory

I read in other bug reports of other software that matplotlib 2.0.0 deprecated set_axis_bgcolor and replaced it with set_facecolor.

Hope this is an easy fix. Any way that I can fix this on my end? I would like to get the plots for my bin refinement results :)

Thanks,
Ilya.

**Comment by ursky** [comment]
Yes, I encountered the error and fixed it. Sorry I haven't pushed the next version yet - im waiting for a few more errors to come in. I just pushed the changes to github, however. To update the scripts on your end, just clone the repository and copy the scripts in `metaWRAP/bin/metawrap-scripts/` into your miniconda installation location (probably something like `~/miniconda2/bin/metawrap-scripts/`.
