### ISSUE TITLE
Something went wrong with CONCOCT and checkM

### ISSUE THREAD

**Issue by YueHuang0911** [bxlab/metaWRAP#155]
Hello,

I met two errors after I updating the numpy to the latest. Could you help me with this? 

Thanks you so much!

When I was doing the initial binning, the CONCOCT was failed. 

`
------------------------------------------------------------------------------------------------------------------------
-----                            Starting binning with CONCOCT. This may take a while...                           -----
------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/envx/miniconda3/envs/metawrap-env/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.4.0', 'concoct')
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 8, in <module>
    from concoct.output import Output
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/output.py", line 11, in <module>
    import pandas as p
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))

ImportError: Missing required dependencies ['numpy']

************************************************************************************************************************
*****                           Something went wrong with binning with CONCOCT. Exiting.                           *****
**************************************************************************************************************************
`

Another happened when I was doing the refinement.

`
------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/envx/miniconda3/envs/metawrap-env/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 23, in <module>
    import numpy as np
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/envx/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/envx/miniconda3/envs/metawrap-env/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named _multiarray_umath

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************
`

**Comment by YueHuang0911** [comment]
Thank you! After re-installing, it works!
