### ISSUE TITLE
Something went wrong when  running binning module with CONCOCT

### ISSUE THREAD

**Issue by zhangws119** [bxlab/metaWRAP#160]
Hi,
When I run the binning module, the matbat2 and maxbin were working normally, but something wrong with CONCOCT.
![1554991658(1)](https://user-images.githubusercontent.com/12234002/56087240-56284e00-5e99-11e9-8d18-85a658ad8331.png)
Could you help me with this? Thank you very much.

**Comment by ursky** [comment]
I think I can fix that. Can you download the `binning.sh` file from this repository and replace your existing `miniconda2/envs/metawrap-env/bin/binning.sh` with it? Then try to re-run and report back. If you use the same output directory you should not have to repeat the read alignment steps.

**Comment by zhangws119** [comment]
> I think I can fix that. Can you download the `binning.sh` file from this repository and replace your existing `miniconda2/envs/metawrap-env/bin/binning.sh` with it? Then try to re-run and report back. If you use the same output directory you should not have to repeat the read alignment steps.

Hi, 

Thanks for your suggestion，I download the 'binning.sh' file, and put it  in 'metawrap-en/bin'. when I run the command with metawrap binning --concoct, it still have the problem as follow: 

########################################################################################################################
#####                                                RUNNING CONCOCT                                               #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                       indexing .bam alignment files...                                       -----
------------------------------------------------------------------------------------------------------------------------

CONCOCT_binning/work_files/XYHsed.bam

------------------------------------------------------------------------------------------------------------------------
-----                             cutting up contigs into 10kb fragments for CONCOCT...                            -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                    estimating contig fragment coverage...                                    -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                       Starting binning with CONCOCT...                                       -----
------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/geobig/User/Softwares/Anaconda2/envs/metawrap-env/bin/concoct", line 6, in <module>
    import vbgmm
ImportError: libgslcblas.so.0: cannot open shared object file: No such file or directory

************************************************************************************************************************
*****                          Something went wrong with binning with CONCOCT. Exiting...                          *****
************************************************************************************************************************

When I only run the command ' concoct ' within metawrap-env, it  still report the same results: 

### (metawrap-env) geobig@geobig-PowerEdge-T640:~/Users/Wensi/XYH_Analysis/pipeline_XYH/INITIAL_BINNING$ concoct
Traceback (most recent call last):
  File "/home/geobig/User/Softwares/Anaconda2/envs/metawrap-env/bin/concoct", line 6, in <module>
    import vbgmm
ImportError: libgslcblas.so.0: cannot open shared object file: No such file or directory


My 'metawrap' version is 1.1.5, could you give me some suggestion?

**Comment by ursky** [comment]
Can you provide the whole output (before concoct starts running)? The new script should fix some library symlinks.

**Comment by ursky** [comment]
Also, definitely update to 1.1.8 first, then update from github.

**Comment by siduanmiao** [comment]
Hello, I met the same problems in my work, I solved this using the following command to install the libgslcblas in your environment.
~~~bash
conda install -c conda-forge libopenblas
~~~
I think the problem is the auther forgetting to add libopenblas into dependency so you have to install it by hand.
