### ISSUE TITLE
binning with concoct in metawrap1.2: pandas.errors.EmptyDataError

### ISSUE THREAD

**Issue by SamLambrechtsUGent** [bxlab/metaWRAP#167]
Dear Ursky,

When running the metawrap binning module with concoct (metawrap v1.2) something went wrong right after the "estimating contig fragment coverage" step. I also noticed that my concoct_depth.txt file as a result is empty. Here is the output:

```
Node type:
 ppn=36, physmem=187GB, swap=0GB, vmem=187GB, local disk=0GB

Currently Loaded Modules:
  1) cluster/skitty                               (S)
  2) GCCcore/7.3.0
  3) binutils/2.30-GCCcore-7.3.0
  4) GCC/7.3.0-2.30
  5) zlib/1.2.11-GCCcore-7.3.0
  6) numactl/2.0.11-GCCcore-7.3.0
  7) hwloc/1.11.10-GCCcore-7.3.0
  8) OpenMPI/3.1.1-GCC-7.3.0-2.30
  9) OpenBLAS/0.3.1-GCC-7.3.0-2.30
 10) gompi/2018b
 11) FFTW/3.3.8-gompi-2018b
 12) ScaLAPACK/2.0.2-gompi-2018b-OpenBLAS-0.3.1
 13) foss/2018b
 14) bzip2/1.0.6-GCCcore-7.3.0
 15) ncurses/6.1-GCCcore-7.3.0
 16) libreadline/7.0-GCCcore-7.3.0
 17) Tcl/8.6.8-GCCcore-7.3.0
 18) SQLite/3.24.0-GCCcore-7.3.0
 19) GMP/6.1.2-GCCcore-7.3.0
 20) libffi/3.2.1-GCCcore-7.3.0
 21) Python/2.7.15-foss-2018b
 22) expat/2.2.5-GCCcore-7.3.0
 23) Perl/5.28.0-GCCcore-7.3.0
 24) libpng/1.6.34-GCCcore-7.3.0
 25) freetype/2.9.1-GCCcore-7.3.0
 26) util-linux/2.32-GCCcore-7.3.0
 27) fontconfig/2.13.0-GCCcore-7.3.0
 28) X11/20180604-GCCcore-7.3.0
 29) nettle/3.4-foss-2018b
 30) libdrm/2.4.92-GCCcore-7.3.0
 31) LLVM/6.0.0-GCCcore-7.3.0
 32) Mesa/18.1.1-foss-2018b
 33) libGLU/9.0.0-foss-2018b
 34) pixman/0.34.0-GCCcore-7.3.0
 35) XZ/5.2.4-GCCcore-7.3.0
 36) libxml2/2.9.8-GCCcore-7.3.0
 37) gettext/0.19.8.1-GCCcore-7.3.0
 38) PCRE/8.41-GCCcore-7.3.0
 39) GLib/2.54.3-GCCcore-7.3.0
 40) cairo/1.14.12-GCCcore-7.3.0
 41) NASM/2.13.03-GCCcore-7.3.0
 42) libjpeg-turbo/2.0.0-GCCcore-7.3.0
 43) LibTIFF/4.0.9-GCCcore-7.3.0
 44) Tk/8.6.8-GCCcore-7.3.0
 45) cURL/7.60.0-GCCcore-7.3.0
 46) Szip/2.1.1-GCCcore-7.3.0
 47) HDF5/1.10.2-foss-2018b
 48) netCDF/4.6.1-foss-2018b
 49) GEOS/3.6.2-foss-2018b-Python-2.7.15
 50) JasPer/2.0.14-GCCcore-7.3.0
 51) PROJ/5.0.0-foss-2018b
 52) libgeotiff/1.4.2-foss-2018b
 53) GDAL/2.2.3-foss-2018b-Python-2.7.15
 54) NLopt/2.4.2-GCCcore-7.3.0
 55) libsndfile/1.0.28-GCCcore-7.3.0
 56) ICU/61.1-GCCcore-7.3.0
 57) UDUNITS/2.2.26-foss-2018b
 58) GSL/2.5-GCC-7.3.0-2.30
 59) R/3.5.1-foss-2018b-Python-2.7.15
 60) SPAdes/3.13.0-foss-2018b
 61) BWA/0.7.17-foss-2018b
 62) MEGAHIT/1.1.4-foss-2018b-Python-2.7.15
 63) Tkinter/2.7.15-foss-2018b-Python-2.7.15
 64) matplotlib/2.2.3-foss-2018b-Python-2.7.15
 65) Boost/1.67.0-foss-2018b
 66) QUAST/5.0.2-foss-2018b-Python-2.7.15
 67) SAMtools/1.9-foss-2018b
 68) MetaBAT/2.12.1-foss-2018b-Python-2.7.15
 69) Biopython/1.72-foss-2018b-Python-2.7.15
 70) scikit-learn/0.20.2-foss-2018b-Python-2.7.15
 71) BamTools/2.5.1-foss-2018b
 72) BEDTools/2.27.1-foss-2018b
 73) picard/2.18.27-Java-1.8
 74) tbb/2018_U5-GCCcore-7.3.0
 75) Bowtie2/2.3.4.2-foss-2018b
 76) parallel/20190222-foss-2018b
 77) Pysam/0.15.1-foss-2018b-Python-2.7.15
 78) pplacer/1.1.alpha19
 79) prodigal/2.6.3-GCCcore-7.3.0
 80) HMMER/3.2.1-foss-2018b
 81) CheckM/1.0.13-foss-2018b-Python-2.7.15
 82) CONCOCT/1.0.0-foss-2018b-Python-2.7.15
 83) FragGeneScan/1.31-foss-2018b
 84) IDBA-UD/1.1.3-foss-2018b
 85) MaxBin/2.2.6-foss-2018b-Perl-5.28.0
 86) Jellyfish/1.1.12-foss-2018b
 87) libidn/1.35-GCCcore-7.3.0
 88) wget/1.20.1-GCCcore-7.3.0
 89) Kraken/1.1-foss-2018b-Perl-5.28.0
 90) KronaTools/2.7-GCCcore-7.3.0
 91) Salmon/0.12.0-foss-2018b
 92) Seaborn/0.9.0-foss-2018b-Python-2.7.15
 93) LMDB/0.9.22-GCCcore-7.3.0
 94) BLAST+/2.7.1-foss-2018b
 95) FastQC/0.11.8-Java-1.8
 96) cutadapt/1.18-foss-2018b-Python-2.7.15
 97) Trim_Galore/0.6.0-foss-2018b-Python-2.7.15
 98) Java/1.8.0_202
 99) NGS/2.9.3-foss-2018b-Java-1.8
100) SRPRISM/3.0.0-foss-2018b
101) bmtagger/3.101-foss-2018b
102) SeqAn/2.4.0-foss-2018b
103) taxator-tk/1.3.3-foss-2018b
104) XML-LibXML/2.0132-GCCcore-7.3.0-Perl-5.28.0
105) BioPerl/1.7.2-foss-2018b-Perl-5.28.0
106) prokka/1.13.4-foss-2018b
107) metaWRAP/1.2-foss-2018b-Python-2.7.15

  Where:
   S:  Module is Sticky, requires --force to unload or purge
metawrap binning -o /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING -t 36 -a /scratch/gent/vo/000/gvo00043/vsc42339/ASSEMBLY/final_assembly.fasta --concoct /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PA_4_2018_1.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PA_4_2018_2.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PA_5_2018_1.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PA_5_2018_2.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_7_2018_1.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_7_2018_2.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_8_2018_1.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_8_2018_2.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_9_2018_1.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_9_2018_2.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_OTC9_10_2018_CON_B_1.fastq /scratch/gent/vo/000/gvo00043/vsc42339/CLEAN_READS/ERR_PB_N_OTC9_10_2018_CON_B_2.fastq

------------------------------------------------------------------------------------------------------------------------
-----                                           Entered read type: paired                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                  6 forward and 6 reverse read files detected                                 -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                     ALIGNING READS TO MAKE COVERAGE FILES                                    #####
########################################################################################################################

Warning: /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING already exists.

------------------------------------------------------------------------------------------------------------------------
-----                         Looks like the assembly file is already coppied. Skipping...                         -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                       Looks like there is a index of the assembly already. Skipping...                       -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                           skipping aligning ERR_PA_4_2018 reads to assembly because                          -----
-----             /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PA_4_2018.bam              -----
-----                                               already exists.                                                -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                           skipping aligning ERR_PA_5_2018 reads to assembly because                          -----
-----             /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PA_5_2018.bam              -----
-----                                               already exists.                                                -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                          skipping aligning ERR_PB_N_7_2018 reads to assembly because                         -----
-----            /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_7_2018.bam             -----
-----                                               already exists.                                                -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                          skipping aligning ERR_PB_N_8_2018 reads to assembly because                         -----
-----            /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_8_2018.bam             -----
-----                                               already exists.                                                -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                          skipping aligning ERR_PB_N_9_2018 reads to assembly because                         -----
-----            /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_9_2018.bam             -----
-----                                               already exists.                                                -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                    skipping aligning ERR_PB_N_OTC9_10_2018_CON_B reads to assembly because                   -----
-----      /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_OTC9_10_2018_CON_B.bam       -----
-----                                               already exists.                                                -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                                RUNNING CONCOCT                                               #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                       indexing .bam alignment files...                                       -----
------------------------------------------------------------------------------------------------------------------------

/scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PA_4_2018.bam
/scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PA_5_2018.bam
/scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_7_2018.bam
/scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_8_2018.bam
/scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_9_2018.bam
/scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/ERR_PB_N_OTC9_10_2018_CON_B.bam

------------------------------------------------------------------------------------------------------------------------
-----                             cutting up contigs into 10kb fragments for CONCOCT...                            -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                    estimating contig fragment coverage...                                    -----
------------------------------------------------------------------------------------------------------------------------

usage: concoct [-h] [--coverage_file COVERAGE_FILE]
               [--composition_file COMPOSITION_FILE] [-c CLUSTERS]
               [-k KMER_LENGTH] [-t THREADS] [-l LENGTH_THRESHOLD]
               [-r READ_LENGTH] [--total_percentage_pca TOTAL_PERCENTAGE_PCA]
               [-b BASENAME] [-s SEED] [-i ITERATIONS] [-e EPSILON]
               [--no_cov_normalization] [--no_total_coverage]
               [--no_original_data] [-o] [-d] [-v]

optional arguments:
  -h, --help            show this help message and exit
  --coverage_file COVERAGE_FILE
                        specify the coverage file, containing a table where
                        each row correspond to a contig, and each column
                        correspond to a sample. The values are the average
                        coverage for this contig in that sample. All values
                        are separated with tabs.
  --composition_file COMPOSITION_FILE
                        specify the composition file, containing sequences in
                        fasta format. It is named the composition file since
                        it is used to calculate the kmer composition (the
                        genomic signature) of each contig.
  -c CLUSTERS, --clusters CLUSTERS
                        specify maximal number of clusters for VGMM, default
                        400.
  -k KMER_LENGTH, --kmer_length KMER_LENGTH
                        specify kmer length, default 4.
  -t THREADS, --threads THREADS
                        Number of threads to use
  -l LENGTH_THRESHOLD, --length_threshold LENGTH_THRESHOLD
                        specify the sequence length threshold, contigs shorter
                        than this value will not be included. Defaults to
                        1000.
  -r READ_LENGTH, --read_length READ_LENGTH
                        specify read length for coverage, default 100
  --total_percentage_pca TOTAL_PERCENTAGE_PCA
                        The percentage of variance explained by the principal
                        components for the combined data.
  -b BASENAME, --basename BASENAME
                        Specify the basename for files or directory where
                        outputwill be placed. Path to existing directory or
                        basenamewith a trailing '/' will be interpreted as a
                        directory.If not provided, current directory will be
                        used.
  -s SEED, --seed SEED  Specify an integer to use as seed for clustering. 0
                        gives a random seed, 1 is the default seed and any
                        other positive integer can be used. Other values give
                        ArgumentTypeError.
  -i ITERATIONS, --iterations ITERATIONS
                        Specify maximum number of iterations for the VBGMM.
                        Default value is 500
  -e EPSILON, --epsilon EPSILON
                        Specify the epsilon for VBGMM. Default value is 1.0e-6
  --no_cov_normalization
                        By default the coverage is normalized with regards to
                        samples, then normalized with regards of contigs and
                        finally log transformed. By setting this flag you skip
                        the normalization and only do log transorm of the
                        coverage.
  --no_total_coverage   By default, the total coverage is added as a new
                        column in the coverage data matrix, independently of
                        coverage normalization but previous to log
                        transformation. Use this tag to escape this behaviour.
  --no_original_data    By default the original data is saved to disk. For big
                        datasets, especially when a large k is used for
                        compositional data, this file can become very large.
                        Use this tag if you don't want to save the original
                        data.
  -o, --converge_out    Write convergence info to files.
  -d, --debug           Debug parameters.
  -v, --version         show program's version number and exit

------------------------------------------------------------------------------------------------------------------------
-----                                       Starting binning with CONCOCT...                                       -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****                          Something went wrong with binning with CONCOCT. Exiting...                          *****
************************************************************************************************************************
```

And the error:

```
Up and running. Check /scratch/gent/vo/000/gvo00043/vsc42339/INITIAL_BINNING/work_files/concoct_out/log.txt for progress
Traceback (most recent call last):
  File "/apps/gent/CO7/skylake-ib/software/CONCOCT/1.0.0-foss-2018b-Python-2.7.15/bin/concoct", line 88, in <module>
    results = main(args)
  File "/apps/gent/CO7/skylake-ib/software/CONCOCT/1.0.0-foss-2018b-Python-2.7.15/bin/concoct", line 20, in main
    composition, cov, cov_range = load_data(args)
  File "/apps/gent/CO7/skylake-ib/software/CONCOCT/1.0.0-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/concoct/input.py", line 25, in load_data
    read_length = args.read_length
  File "/apps/gent/CO7/skylake-ib/software/CONCOCT/1.0.0-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/concoct/input.py", line 82, in load_coverage
    cov = p.read_table(cov_file, header=0, index_col=0)
  File "/apps/gent/CO7/skylake-ib/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/pandas-0.23.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/apps/gent/CO7/skylake-ib/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/pandas-0.23.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/apps/gent/CO7/skylake-ib/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/pandas-0.23.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/apps/gent/CO7/skylake-ib/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/pandas-0.23.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/apps/gent/CO7/skylake-ib/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/pandas-0.23.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

real	36m5.281s
user	37m8.285s
sys	1m53.222s

```

**Comment by ursky** [comment]
It looks like the program is skipping alignment because some older files are present in the output directory. Its possible that this is causing this. Can you re-run with a fresh output folder and see if that fixes it?
