### ISSUE TITLE
Plotting error during bin_refinement

### ISSUE THREAD

**Issue by mb1069** [bxlab/metaWRAP#179]
```
------------------------------------------------------------------------------------------------------------------------
-----                making completion and contamination ranking plots for all refinement iterations               -----
-----------------------------------------------------------------------------------------------
-------------------------

Loading completion info....
Plotting completion data...
Traceback (most recent call last):
  File "/usr/local/bin/metawrap-scripts/plot_binning_results.py", line 109, in <module>
    y_pos = data[bin_set][len(data[bin_set])*3/4]
IndexError: list index out of range
mv: can't rename 'binning_results.eps': No such file or directory
mv: can't rename 'binning_results.png': No such file or directory
```

The issue above occurs right at the end of the binning process, I am running v1.2 via the docker container. the full error is can be found here:
https://gist.github.com/mb1069/1b4c2be42a8c787f91c7dfa365a95592

Cheers,
Miguel

**Comment by ursky** [comment]
Thanks for the detailed report! Looks like you have a single good bin in your refinement output. The plotting functiton is not designed to handle that - why plot a completion/contamination decay curve of a single bin?

**Comment by mb1069** [comment]
Fair point, thank you for responding so promptly! I suppose a warning message may be worthwhile to avoid other reports of this issue?

**Comment by franciscozorrilla** [comment]
I noticed that I get the same error message even though I have 5 bins that passed the bin refinement (toy example).

```
./plot_binning_results.py 50 10 sample3.concoct-bins.stats sample3.metabat-bins.stats sample3.maxbin-bins.stats metawrap_50_10_bins.stats 

Loading completion info....
Plotting completion data...
Traceback (most recent call last):
  File "./plot_binning_results.py", line 109, in <module>
    y_pos = data[bin_set][len(data[bin_set])*3/4]
IndexError: list index out of range 
```
Then I checked my maxbin output and noticed that it only produced 1 good bin: 

```
bin	completeness	contamination	GC	lineage	N50	size	binner
sample3.001	98.24	39.02	0.336	Bacteria	44181	3501895	binsC
sample3.002	96.39	39.10	0.613	Bacteria	4473	3029585	binsC
sample3.003	92.94	35.92	0.549	Bacteria	3356	4341120	binsC
sample3.004	50.85	27.61	0.443	Bacteria	1662	3589661	binsC
sample3.005	95.67	51.65	0.492	Clostridia	3291	2773229	binsC
sample3.006	19.75	5.607	0.391	Archaea	1718	2247873	binsC
```

The problem was resolved by omitting the maxbin input from the plot_binning_refinement.py call:

```
./plot_binning_results.py 50 10 sample3.concoct-bins.stats sample3.metabat-bins.stats metawrap_50_10_bins.stats 
Loading completion info....
Plotting completion data...
Loading contamination info...
Plotting the contamination data...
Saving figures binning_results.eps and binning_results.png ...
```

Perhaps the script should be modified to check and remove any problematic binning inputs, since the error is thrown even when there is more than 1 refined bin produced.
