### ISSUE TITLE
bin_refinement checkm

### ISSUE THREAD

**Issue by hqtdave** [bxlab/metaWRAP#180]
Hi all,

I'm running bin_refinement but when it came to the checkm part, I keep getting this kind of issue:
```
>   Identifying marker genes in 72 bins with 1 threads:
> Process SyncManager-1:
> Traceback (most recent call last):
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
>     self.run()
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
>     server = cls._Server(registry, address, authkey, serializer)
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
>     self.listener = Listener(address=address, backlog=16)
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
>     self._listener = SocketListener(address, family, backlog)
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
>     self._socket.bind(address)
>   File "/home/hienthanh/anaconda2/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> error: [Errno 22] Invalid argument
> 
> Unexpected error: <type 'exceptions.EOFError'>
> Traceback (most recent call last):
>   File "/home/hienthanh/anaconda2/bin/checkm", line 708, in <module>
>     checkmParser.parseOptions(args)
>   File "/home/hienthanh/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
>     self.tree(options)
>   File "/home/hienthanh/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 133, in tree
>     options.bCalledGenes)
>   File "/home/hienthanh/anaconda2/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 67, in find
>     binIdToModels = mp.Manager().dict()
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
>     m.start()
>   File "/home/hienthanh/anaconda2/lib/python2.7/multiprocessing/managers.py", line 528, in start
>     self._address = reader.recv()
> EOFError
```
Where is the problem? And how can I fix it? I have tried to reinstall metawrap couple times but cannot pass this one.

**Comment by ursky** [comment]
I don't recall ever seeing this error from CheckM. Can you open an issue on their github as well?
