### ISSUE TITLE
how to continue the bin_refinemet module?

### ISSUE THREAD

**Issue by cczhao2018** [bxlab/metaWRAP#189]
[fat_bin_refinement1.2.log](https://github.com/bxlab/metaWRAP/files/3255586/fat_bin_refinement1.2.log)

[fat_bin_refinement1.2.err.log](https://github.com/bxlab/metaWRAP/files/3255631/fat_bin_refinement1.2.err.log)

Hi, Ursky. 
I got too many bins when I want to continue the bin_refinement module, the software trying to delete the previously finished files. Because I didn't see any .stats files like you written in the changelog. Please help me to check whether I meet the checkpoint for .stats files producing.

Thanks for your support!

**Comment by ursky** [comment]
Hey there! Previously the checkpoint only allowed to skip previous CheckM runs if the pipeline completed at least once previously. This was implemented for repeated runs with different `-x` and `-c` parameters. 

I added additional checkpoints to the program to skip previously completer CheckM runs. So if your job times out, rust re-run it and it should get further. These changes are only on github for now, so clone the repository and replace your `bin_refinment.sh` with the one in this repository. Or just follow the "manual installation" instructions. 

Let me know how the fix works for you.

**Comment by cczhao2018** [comment]
Sorry for the late reply, because, there is a long queue in our public server.
I replaced the bin_refinment.sh and reran this module, however, It still attempts to clean previous outputs and looks don't work. As for my job, It just began to run CheckM then kill because of time up. So I think could we add another checkpoint like that to see whether the outputs are qualified for the following CheckM running. 
Thank you so much!

here are my log files may help you:
[144fat_bin_refinement1.2.log](https://github.com/bxlab/metaWRAP/files/3285845/144fat_bin_refinement1.2.log)
[144fat_bin_refinement1.2.err.log](https://github.com/bxlab/metaWRAP/files/3285847/144fat_bin_refinement1.2.err.log)

**Comment by ursky** [comment]
Looks like you are running out of time even before one set finishes. I dont think you can do regular refinement in this case, unfortunately. You have three options: skip the refinement altogether and go with one bin set (metabat2 is the best one usually), re-run the refinement but with only the promising bins, or do the refinement manually, step by step. 

To make the job go faster you could remove some of the bad bins from your sets, greatly accelerating the job. I would remove any bins <1MB or >6MB - this would condense the sets considerably. You could then proceed with the 3 curated sets, or maybe even drop down to just 2 sets that look most promising (use just A and B).

To run manually you can use your current progress. You already have the 3 sets (A, B, C) plus the 4 refined sets (AB, BC, AC, ABC) in the output, so you have a starting point. Look at the refinement.sh code and see how CheckM and the summary scripts are run to produce the `.stats` files. Once you have those, you can run the loop that consolidates the 7 sets together into binsM/binsO. Basically, if you know a tiny bit of Unix you should be able to implement the core line by line, moving and copying the folders however you like.

**Comment by cczhao2018** [comment]
Thank you so much for your constructive suggestion, I will try to refine BinsA and BinsB firstly.

**Comment by cczhao2018** [comment]
Thank you so much for your constructive suggestions, I will try to refine BinsA and BinsB firstly.

**Comment by B-1991-ing** [comment]
Dear cczhao,

I found some error lines in your file - [144fat_bin_refinement1.2.err.log](https://github.com/bxlab/metaWRAP/files/3285847/144fat_bin_refinement1.2.err.log). But did you regard this as an real error or just a warning message?

Traceback (most recent call last):
  File "/home/liuhaiyan/cczhao/anaconda3/envs/metawrap1.2/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/home/liuhaiyan/cczhao/anaconda3/envs/metawrap1.2/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/liuhaiyan/cczhao/anaconda3/envs/metawrap1.2/lib/python2.7/shutil.py", line 270, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/liuhaiyan/cczhao/anaconda3/envs/metawrap1.2/lib/python2.7/shutil.py", line 268, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'binsA.tmp/pymp-XmGtEe'
  Saving HMM info to file.

I actually also have similar error message in my error file now. So I am checking what's wrong there.

**Mine error message is like below.**
Traceback (most recent call last):
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-0rFgAr/.nfs00000006f80c7eaf0000313c'

Best,

Bing
