### ISSUE TITLE
checkm error during bin_refinement

### ISSUE THREAD

**Issue by mb1069** [bxlab/metaWRAP#191]
Hi,
I'm encountering the following problem when running the bin_refinement step on some bins;

```
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 2 bins with 1 threads:
Process SyncManager-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/opt/conda/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/opt/conda/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/opt/conda/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/opt/conda/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/opt/conda/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/opt/conda/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/opt/conda/lib/python2.7/site-packages/checkm/main.py", line 133, in tree
    options.bCalledGenes)
  File "/opt/conda/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 67, in find

Unexpected error: <type 'exceptions.EOFError'>
    binIdToModels = mp.Manager().dict()
  File "/opt/conda/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/opt/conda/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError

```

The full output is here:
https://gist.github.com/mb1069/492b88e7dadf9a457b2757128b6aae50

**Comment by ursky** [comment]
Interesting. Can you run CheckM manually on the problematic bin set? This is a CheckM issue not metawrap, i think. If it is, could you open up an issue on their github and post the link? I dont know enough about CheckM's inner workings to understand the source of this error.

**Comment by mb1069** [comment]
Hi Ursky,
I've looked into the error and noticed that it only occurs if using the --tmpdir option;
In bin_refinement.sh (https://github.com/bxlab/metaWRAP/blob/17256691e09c6eb596ca0426f015ac2c21453d00/bin/metawrap-modules/bin_refinement.sh#L267) the function works if I remove the --tmpdir option, but fails otherwise.

**Comment by ursky** [comment]
Where is `${bin_set}.tmp` exactly, in your run? Can you insert a print statement like `comm ${bin_set}.tmp` before checkm runs and check if this is a valid location? I originally enforced this option to reduce accidental permission breaches on some systems.

**Comment by mb1069** [comment]
I believe the code cd's to a different directory (?) so the path set was "binsA.tmp"

**Comment by ursky** [comment]
Can you print `$(pwd)/${bin_set}.tmp` then?

**Comment by mb1069** [comment]
/mnt/tara_binning/outputs/ERR164407/refined_bins/binsA.tmp, and the dir appears to exist. However if I put the --tmpdir option back in checkm fails.

**Comment by ursky** [comment]
Very strange. Could you still open a CheckM github issue and link this? This might be useful for them. In the meantime, feel free to eliminate this option from the metawrap scripts. I might consider adding a `--tmpdir` option to metawrap itself in the future to allow better control, but for now I dont want to just remove this option - it actually helped remove some other errors users have reported.

**Comment by mb1069** [comment]
Will do, thank you. For future reference, I am using checkm=1.0.12
