### ISSUE TITLE
checkm data setRoot error : no matplotlb.backends.backend.agg

### ISSUE THREAD

**Issue by raissafedora** [bxlab/metaWRAP#201]
Hi I tried installing checkm database but the setRoot returned this error:
```
Traceback (most recent call last):
  File "/scratch/users/nus/bchref/.conda/metawrap/bin/checkm", line 36, in <module>
    from checkm import main
  File "/scratch/users/nus/bchref/.conda/metawrap/lib/python2.7/site-packages/checkm/main.py", line 49, in <module>
    from checkm.plot.gcPlots import GcPlots
  File "/scratch/users/nus/bchref/.conda/metawrap/lib/python2.7/site-packages/checkm/plot/gcPlots.py", line 24, in <module>
    from AbstractPlot import AbstractPlot
  File "/scratch/users/nus/bchref/.conda/metawrap/lib/python2.7/site-packages/checkm/plot/AbstractPlot.py", line 22, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
```
I've updated all the deps so I don't know what causing the error now . What do I do?

**Comment by ursky** [comment]
Is matplotlib installed?

**Comment by raissafedora** [comment]
Yep. I made sure it's installed.

**Comment by ursky** [comment]
Hmm... i've never seen this error. Could you open an issue in the CheckM github https://github.com/Ecogenomics/CheckM and link this thread? CheckM devs might know more, and are usually very responsive.

**Comment by raissafedora** [comment]
FINALLY. I figured out the problem.
I'm not sure why, but anaconda didn't link user site-packages.
so, I have to manually add this into the bin/checkm

```
import site
site.addsitedir("path/to/conda/.conda/metawrap/lib/python2.7/site-packages")

This happens in #2 about concoct vbgmm as well, so I am guessing this is all linking error. This is temporary fix, though. I am not sure how to apply this fix environment-wide ._.

**Comment by chassenr** [comment]
Hi @raissafedora @ursky ,
do you have any updates regarding this issue? There has been no response to the issue by the checkm developers.
I have the same problem that any checkm command breaks with same error message. I am using checkm version 1.0.18 (latest python2 release). I tried to implement your fix @raissafedora by adding the lines ```import site``` and ```site.addsitedir("/opt/miniconda2/lib/python2.7/site-packages")``` (which is the location of my python packages) to the checkm source code and installing it with ```python setup.py install``` but the installation did not work properly (error message: ```pkg_resources.ResolutionError: Script 'scripts/checkm' not found in metadata at '/opt/miniconda2/lib/python2.7/site-packages/checkm_genome-1.0.18.dist-info'```). Can you provide more details about how you solved the issue?

Thank you so much for your help! 

Best,
Christiane

**Comment by raissafedora** [comment]
Hi Christiane, 
is it by any chance you link the miniconda python packages instead of metawrap? try linking python packages from where you install metawrap.

**Comment by chassenr** [comment]
Hi @raissafedora ,
I did not install metawrap in its own environment if this what you meant and there are no python packages installed in the metawrap location. I also have the impression that the issue is related to the checkm version. Installing checkm for python 3 worked without any problems. In the end, I managed to solve the issue by removing the python 2 checkm installation (conda remove --force) and installing python 3 checkm. Then I made sure that in my $PATH the python 2 bin came first before the python 3 bin, and I ran metawrap. This worked (apart from a matplotlib error ```No module named matplotlib.pyplot``` when executing plot_binning_results.py).
