### ISSUE TITLE
checkm error bin_refinement (Models must be parsed before identifying HMM hits)

### ISSUE THREAD

**Issue by mb1069** [bxlab/metaWRAP#203]
I'm getting the following error when running bin refinement
```
########################################################################################################################
#####                                      RUNNING CHECKM ON ALL SETS OF BINS                                      #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                   Note: running with --reduced_tree option                                   -----
------------------------------------------------------------------------------------------------------------------------


*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 4 threads:
    Finished processing 0 of 1 (0.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 4 threads:
    Finished processing 0 of 1 (0.00%) bins.
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.

Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/mnt/tara_binning/CWL_binning/venv/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/mnt/tara_binning/CWL_binning/venv/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/mnt/tara_binning/CWL_binning/venv/lib/python2.7/site-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/mnt/tara_binning/CWL_binning/venv/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 105, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/mnt/tara_binning/CWL_binning/venv/lib/python2.7/site-packages/checkm/resultsParser.py", line 85, in parseBinHits
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************
```

The full log is available here
https://gist.github.com/mb1069/cc5ec849bd72c7290590c202011cca88

**Comment by ursky** [comment]
Could you have a look at the bins inside OUT/binsA and make sure everything seems ok? And has the database been installed? I have never seen this error. Perhaps ask the CheckM team?

**Comment by slambrechts** [comment]
I'm experiencing the same error

**Comment by liying-lan** [comment]
Did you solve the problem? I'm experiencing the same error
