### ISSUE TITLE
quant bin fail error when making the the heatmap and  abundance table didn't contain three samples

### ISSUE THREAD

**Issue by yuhe4046** [bxlab/metaWRAP#212]
I used metaWRAP v=1.2.1. I , but quant bin failed error when making the the heatmap, and  abundance table didn't contain three samples (I have three samples).

here is the results:

metawrap quant_bins -o sep_QUANT_BINS -t 40 -a /share/home/yuhe/a/metogenome/0612.SH.ASSEMBLY/final_assembly.fasta -b /share/home/yuhe/data/MY_CHECKM_FOLDER/SH.70.5BIN_REFINEMENT/metawrap_70_5_bins /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R12_1.fastq /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R12_2.fastq /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R13_1.fastq /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R13_2.fastq /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R19_1.fastq /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R19_2.fastq

------------------------------------------------------------------------------------------------------------------------
-----                                  3 forward and 3 reverse read files detected                                 -----
------------------------------------------------------------------------------------------------------------------------

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                            Indexing assembly file with salmon. Ignore any warnings                           -----
------------------------------------------------------------------------------------------------------------------------

Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
index ["sep_QUANT_BINS/assembly_index"] did not previously exist  . . . creating it
[2019-07-22 11:34:07.054] [jLog] [info] building index
[2019-07-22 11:34:07.063] [jointLog] [info] [Step 1 of 4] : counting k-mers
[2019-07-22 11:34:07.331] [jointLog] [warning] Entry with header [k141_5071203_length_501818_cov_27.9845] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.353] [jointLog] [warning] Entry with header [k141_5054086_length_476307_cov_29.5229] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.366] [jointLog] [warning] Entry with header [k141_3427556_length_310886_cov_35.8781] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.378] [jointLog] [warning] Entry with header [k141_3562351_length_272351_cov_24.3273] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.387] [jointLog] [warning] Entry with header [k141_30697_length_268395_cov_28.3423] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.397] [jointLog] [warning] Entry with header [k141_2669835_length_238160_cov_45.0131] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.405] [jointLog] [warning] Entry with header [k141_4108769_length_237011_cov_34.1919] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.412] [jointLog] [warning] Entry with header [k141_2085658_length_223236_cov_77.8299] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.418] [jointLog] [warning] Entry with header [k141_3595791_length_205026_cov_32.1201] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.426] [jointLog] [warning] Entry with header [k141_1133550_length_203510_cov_21.3044] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
[2019-07-22 11:34:07.432] [jointLog] [warning] Entry with header [k141_4926892_length_201778_cov_52.0528] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?
counted k-mers for 950,000 transcriptsElapsed time: 58.9741s

[2019-07-22 11:35:06.043] [jointLog] [info] Replaced 0 non-ATCG nucleotides
[2019-07-22 11:35:06.043] [jointLog] [info] Clipped poly-A tails from 61 transcripts
[2019-07-22 11:35:06.135] [jointLog] [info] Building rank-select dictionary and saving to disk
[2019-07-22 11:35:06.326] [jointLog] [info] done
Elapsed time: 0.19097s
[2019-07-22 11:35:07.205] [jointLog] [info] Writing sequence data to file . . . 
[2019-07-22 11:35:09.059] [jointLog] [info] done
Elapsed time: 1.85373s
[2019-07-22 11:35:14.431] [jointLog] [info] Building 64-bit suffix array (length of generalized text is 2,395,266,018)
[2019-07-22 11:38:05.314] [jointLog] [info] Building suffix array . . . 
success
saving to disk . . . done
Elapsed time: 16.7204s
done
Elapsed time: 680.213s
processed 2,395,000,000 positions[2019-07-22 13:15:55.500] [jointLog] [info] khash had 2,325,282,560 keys
[2019-07-22 13:15:55.531] [jointLog] [info] saving hash to disk . . . 
[2019-07-22 13:22:37.641] [jointLog] [info] done
Elapsed time: 402.11s
[2019-07-22 13:24:11.480] [jLog] [info] done building index

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                                      processing sample SH.R12 with reads                                     -----
-----             /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R12_1.fastq and             -----
-----             /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R12_2.fastq...              -----
------------------------------------------------------------------------------------------------------------------------

### [ threads ] => { 40 }
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
Logs will be written to sep_QUANT_BINS/alignment_files/SH.R12.quant/logs
[2019-07-22 13:24:14.835] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2019-07-22 13:24:14.835] [jointLog] [warning] 

NOTE: It appears you are running salmon without the `--validateMappings` option.
Mapping validation can generally improve both the sensitivity and specificity of mapping,
with only a moderate increase in use of computational resources. 
Mapping validation is planned to become a default option (i.e. turned on by default) in
the next release of salmon.
Unless there is a specific reason to do this (e.g. testing on clean simulated data),
`--validateMappings` is generally recommended.

[2019-07-22 13:24:14.835] [jointLog] [info] parsing read library format
[2019-07-22 13:24:14.835] [jointLog] [info] There is 1 library.
[2019-07-22 13:24:14.931] [jointLog] [info] Loading Quasi index
[2019-07-22 13:24:14.931] [jointLog] [info] Loading 64-bit quasi index
[2019-07-22 13:24:14.931] [stderrLog] [info] Loading Suffix Array 
[2019-07-22 13:25:01.014] [stderrLog] [info] Loading Transcript Info 
[2019-07-22 13:25:11.146] [stderrLog] [info] Loading Rank-Select Bit Array
[2019-07-22 13:25:12.737] [stderrLog] [info] There were 956,861 set bits in the bit array
[2019-07-22 13:25:12.979] [stderrLog] [info] Computing transcript lengths
[2019-07-22 13:25:12.982] [stderrLog] [info] Waiting to finish loading hash
[2019-07-22 13:30:51.380] [jointLog] [info] done
[2019-07-22 13:30:51.380] [jointLog] [info] Index contained 956,861 targets
[2019-07-22 13:30:51.380] [stderrLog] [info] Done loading index

processed 94,500,000 fragments
hits: 60,443,475, hits per frag:  0.640319

[2019-07-22 13:36:05.881] [jointLog] [info] Computed 1,099,689 rich equivalence classes for further processing
[2019-07-22 13:36:05.881] [jointLog] [info] Counted 59,999,312 total reads in the equivalence classes 
[2019-07-22 13:36:05.965] [jointLog] [warning] 0.000185788% of fragments were shorter than the k used to build the index (31).
If this fraction is too large, consider re-building the index with a smaller k.
The minimum read size found was 20.

[2019-07-22 13:36:05.965] [jointLog] [info] Number of fragments discarded because they have only dovetail (discordant) mappings : 119,212
[2019-07-22 13:36:05.965] [jointLog] [info] Mapping rate = 63.336%

[2019-07-22 13:36:05.965] [jointLog] [info] finished quantifyLibrary()
[2019-07-22 13:36:06.043] [jointLog] [info] Starting optimizer
[2019-07-22 13:36:06.645] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2019-07-22 13:36:06.660] [jointLog] [info] iteration = 0 | max rel diff. = 499.942
[2019-07-22 13:36:07.617] [jointLog] [info] iteration = 100 | max rel diff. = 7.83688e-16
[2019-07-22 13:36:07.638] [jointLog] [info] Finished optimizer
[2019-07-22 13:36:07.638] [jointLog] [info] writing output 

------------------------------------------------------------------------------------------------------------------------
-----                                      processing sample SH.R13 with reads                                     -----
-----             /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R13_1.fastq and             -----
-----             /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R13_2.fastq...              -----
------------------------------------------------------------------------------------------------------------------------

### [ threads ] => { 40 }
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
Logs will be written to sep_QUANT_BINS/alignment_files/SH.R13.quant/logs
[2019-07-22 13:36:19.989] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2019-07-22 13:36:19.989] [jointLog] [warning] 

NOTE: It appears you are running salmon without the `--validateMappings` option.
Mapping validation can generally improve both the sensitivity and specificity of mapping,
with only a moderate increase in use of computational resources. 
Mapping validation is planned to become a default option (i.e. turned on by default) in
the next release of salmon.
Unless there is a specific reason to do this (e.g. testing on clean simulated data),
`--validateMappings` is generally recommended.

[2019-07-22 13:36:19.989] [jointLog] [info] parsing read library format
[2019-07-22 13:36:19.989] [jointLog] [info] There is 1 library.
[2019-07-22 13:36:20.090] [jointLog] [info] Loading Quasi index
[2019-07-22 13:36:20.090] [jointLog] [info] Loading 64-bit quasi index
[2019-07-22 13:36:20.106] [stderrLog] [info] Loading Suffix Array 
[2019-07-22 13:36:58.424] [stderrLog] [info] Loading Transcript Info 
[2019-07-22 13:37:00.160] [stderrLog] [info] Loading Rank-Select Bit Array
[2019-07-22 13:37:00.481] [stderrLog] [info] There were 956,861 set bits in the bit array
[2019-07-22 13:37:00.637] [stderrLog] [info] Computing transcript lengths
[2019-07-22 13:37:00.641] [stderrLog] [info] Waiting to finish loading hash
[2019-07-22 13:43:47.934] [stderrLog] [info] Done loading index
[2019-07-22 13:43:47.934] [jointLog] [info] done
[2019-07-22 13:43:47.934] [jointLog] [info] Index contained 956,861 targets

processed 96,500,000 fragments
hits: 60,383,942, hits per frag:  0.626929

[2019-07-22 13:49:22.985] [jointLog] [info] Computed 1,106,567 rich equivalence classes for further processing
[2019-07-22 13:49:22.985] [jointLog] [info] Counted 59,623,346 total reads in the equivalence classes 

[2019-07-22 13:49:23.017] [jointLog] [warning] 0.000271435% of fragments were shorter than the k used to build the index (31).
If this fraction is too large, consider re-building the index with a smaller k.
The minimum read size found was 20.

[2019-07-22 13:49:23.017] [jointLog] [info] Number of fragments discarded because they have only dovetail (discordant) mappings : 134,236
[2019-07-22 13:49:23.017] [jointLog] [info] Mapping rate = 61.7705%

[2019-07-22 13:49:23.017] [jointLog] [info] finished quantifyLibrary()
[2019-07-22 13:49:23.085] [jointLog] [info] Starting optimizer
[2019-07-22 13:49:23.667] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2019-07-22 13:49:23.679] [jointLog] [info] iteration = 0 | max rel diff. = 499.844
[2019-07-22 13:49:24.620] [jointLog] [info] iteration = 100 | max rel diff. = 0.00380135
[2019-07-22 13:49:24.641] [jointLog] [info] Finished optimizer
[2019-07-22 13:49:24.641] [jointLog] [info] writing output 

------------------------------------------------------------------------------------------------------------------------
-----                                      processing sample SH.R19 with reads                                     -----
-----             /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R19_1.fastq and             -----
-----             /share/home/yuhe/a/metogenome/Rawdta/metawrap.clean.data/SH.R19_2.fastq...              -----
------------------------------------------------------------------------------------------------------------------------

### [ threads ] => { 40 }
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
Logs will be written to sep_QUANT_BINS/alignment_files/SH.R19.quant/logs
[2019-07-22 13:49:37.127] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2019-07-22 13:49:37.127] [jointLog] [warning] 

NOTE: It appears you are running salmon without the `--validateMappings` option.
Mapping validation can generally improve both the sensitivity and specificity of mapping,
with only a moderate increase in use of computational resources. 
Mapping validation is planned to become a default option (i.e. turned on by default) in
the next release of salmon.
Unless there is a specific reason to do this (e.g. testing on clean simulated data),
`--validateMappings` is generally recommended.

[2019-07-22 13:49:37.127] [jointLog] [info] parsing read library format
[2019-07-22 13:49:37.127] [jointLog] [info] There is 1 library.
[2019-07-22 13:49:37.243] [jointLog] [info] Loading Quasi index
[2019-07-22 13:49:37.243] [jointLog] [info] Loading 64-bit quasi index
[2019-07-22 13:49:37.244] [stderrLog] [info] Loading Suffix Array 
[2019-07-22 13:49:50.533] [stderrLog] [info] Loading Transcript Info 
[2019-07-22 13:49:52.334] [stderrLog] [info] Loading Rank-Select Bit Array
[2019-07-22 13:49:52.662] [stderrLog] [info] There were 956,861 set bits in the bit array
[2019-07-22 13:49:52.829] [stderrLog] [info] Computing transcript lengths
[2019-07-22 13:49:52.833] [stderrLog] [info] Waiting to finish loading hash
[2019-07-22 13:53:12.490] [jointLog] [info] done
[2019-07-22 13:53:12.490] [jointLog] [info] Index contained 956,861 targets
[2019-07-22 13:53:12.490] [stderrLog] [info] Done loading index

processed 88,000,000 fragments
hits: 54,591,362, hits per frag:  0.621314

[2019-07-22 13:58:14.981] [jointLog] [info] Computed 1,074,246 rich equivalence classes for further processing
[2019-07-22 13:58:14.981] [jointLog] [info] Counted 53,970,172 total reads in the equivalence classes 
[2019-07-22 13:58:15.012] [jointLog] [warning] 0.000233768% of fragments were shorter than the k used to build the index (31).
If this fraction is too large, consider re-building the index with a smaller k.
The minimum read size found was 20.

[2019-07-22 13:58:15.012] [jointLog] [info] Number of fragments discarded because they have only dovetail (discordant) mappings : 133,632
[2019-07-22 13:58:15.012] [jointLog] [info] Mapping rate = 61.245%

[2019-07-22 13:58:15.012] [jointLog] [info] finished quantifyLibrary()
[2019-07-22 13:58:15.014] [jointLog] [info] Starting optimizer
[2019-07-22 13:58:15.549] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2019-07-22 13:58:15.558] [jointLog] [info] iteration = 0 | max rel diff. = 499.75
[2019-07-22 13:58:16.410] [jointLog] [info] iteration = 100 | max rel diff. = 0.00857305
[2019-07-22 13:58:16.431] [jointLog] [info] Finished optimizer
[2019-07-22 13:58:16.431] [jointLog] [info] writing output 

------------------------------------------------------------------------------------------------------------------------
-----                                           summarize salmon files...                                          -----
------------------------------------------------------------------------------------------------------------------------

Starting in: /share/home/yuhe/a/metogenome/0612.SH.ASSEMBLY/sep_QUANT_BINS/alignment_files
Loading counts from: ./SH.R12.quant quant.sf
Loading counts from: ./SH.R13.quant quant.sf
Loading counts from: ./SH.R19.quant quant.sf
"SH.R12.quant.counts",
"SH.R13.quant.counts",
"SH.R19.quant.counts"

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                            There were 3 samples detected. Making abundance table!                            -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                   Average bin abundance table stored in sep_QUANT_BINS/abundance_table.tab                   -----
------------------------------------------------------------------------------------------------------------------------

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                                          making heatmap with Seaborn                                         -----
------------------------------------------------------------------------------------------------------------------------

loading libs...
loading abundance data...
drawing clustermap...
Traceback (most recent call last):
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/bin/metawrap-scripts/make_heatmap.py", line 75, in <module>
    draw_clustermap(df, lut)
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/bin/metawrap-scripts/make_heatmap.py", line 58, in draw_clustermap
    g = sns.clustermap(df, figsize=(14,8), col_cluster=True, yticklabels=True, cmap="magma")
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 1301, in clustermap
    **kwargs)
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 1128, in plot
    row_linkage=row_linkage, col_linkage=col_linkage)
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 1029, in plot_dendrograms
    axis=1, ax=self.ax_col_dendrogram, linkage=col_linkage)
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 747, in dendrogram
    label=label, rotate=rotate)
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 564, in __init__
    self.linkage = self.calculated_linkage
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 628, in calculated_linkage
    return self._calculate_linkage_scipy()
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 603, in _calculate_linkage_scipy
    metric=self.metric)
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 1112, in linkage
    n = int(distance.num_obs_y(y))
  File "/share/home/yuhe/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/scipy/spatial/distance.py", line 2384, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.

************************************************************************************************************************
*****                           something went wrong with making the heatmap. Exiting...                           *****
************************************************************************************************************************

real	145m4.479s
user	349m16.552s
sys	59m31.502s

**Comment by yuhe4046** [comment]
here is part of the bin_abundance_table.tab :
Genomic bins	SH
bin.18	2.20254029002
bin.9	0.773597863849
bin.52	0.89788971205
bin.20	1.44597658633
bin.36	2.06748446356
bin.4	1.931248483
bin.25	0.980918497947
bin.22	0.664894156701
bin.6	0.754933941053
bin.27	1.94009149691
bin.15	1.14162389861
bin.70	1.2996628985

**Comment by yuhe4046** [comment]
but I gou the following quant.counts from three samples:
 [yuhe@login sep_QUANT_BINS]$ cd quant_files/
 [yuhe@login quant_files]$ ll
total 127440
-rw-rw-r-- 1 yuhe yuhe 43513263 Jul 22 13:58 SH.R12.quant.counts
-rw-rw-r-- 1 yuhe yuhe 43504597 Jul 22 13:58 SH.R13.quant.counts
-rw-rw-r-- 1 yuhe yuhe 43472067 Jul 22 13:58 SH.R19.quant.counts

here is the part of SH.R12.quant.counts:
transcript	count
k141_5071203_length_501818_cov_27.9845	1.44818
k141_5054086_length_476307_cov_29.5229	1.066772
k141_3427556_length_310886_cov_35.8781	1.56786
k141_3562351_length_272351_cov_24.3273	0.995997
k141_30697_length_268395_cov_28.3423	1.473437
k141_2669835_length_238160_cov_45.0131	2.326152
k141_4108769_length_237011_cov_34.1919	1.209103
k141_2085658_length_223236_cov_77.8299	5.532826
k141_3595791_length_205026_cov_32.1201	1.156389

**Comment by ursky** [comment]
The program cannot make a clustered heatmap from just one column. You need at least 3.

**Comment by ursky** [comment]
Wait, I just saw the second part of your response. I think what is happening is that the program takes the name of each sample to be everything before a `.`, so all your samples get abbreviated to be `SH`. I'll work to fix this bug, but the easiest thing you can probably do in the meantime is changing the names to `SH_R12` instead of `SH.R12`.
