### ISSUE TITLE
Error checkm in Binning procedure

### ISSUE THREAD

**Issue by Thexiyang** [bxlab/metaWRAP#22]
Hi,

I have run the binning module, using metabat2, maxbin2, concoct, plus checkm. here is the error message. it is still running. i would like to know if this is a big problem, as it looks the final checkm results looks all fine. 

**during metabat2 binning:** 
```
*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 536 bins with 40 threads:
    Finished processing 536 of 536 (100.00%) bins.
Traceback (most recent call last):
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '.tmp/pymp-NioJzr/.nfs000000002876a5af00000527'
  Saving HMM info to file.
```

**during maxbin2 binning:**
```
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 549 bins with 40 threads:
    Finished processing 549 of 549 (100.00%) bins.
Traceback (most recent call last):
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/export/data/programs/pyenv/versions/2.7.9/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'bin.549.fasta.tmp/pymp-GrvYbX/.nfs000000002827d9320000074f'
  Saving HMM info to file.
```

Thanks in advance.

**Comment by ursky** [comment]
Thanks for the feedback! If you don't mind, can you give me some info about what the output folder looks like after? Especially the '.checkm' folders and .stats files (if there are any). Sometimes CheckM gives me strange errors but then finishes fine. If CheckM actually failed, then metaWRAP is instructed to exit (or at least it should...).

**Comment by Thexiyang** [comment]
Thanks for the response. The output folders look all fine: `bins`, `lineage.m`, `storage`  in .`checkm`  folder and also there is `.stats` folder. They are all with reasonable data there for both maxbin2 and metabat2. It seems that it worked out. I am following the whole pipeline and probably can give you further feedback on this during the refine step where checkm will be used more often. 

Ps: how slow is the concoct binning process? It has been like this since 20 hours ago and there is nothing changes for the log file since the starting point. Should I just kill it?


```
------------------------------------------------------------------------------------------------------------------------
-----                            Starting binning with CONCOCT. This may take a while...                           -----
------------------------------------------------------------------------------------------------------------------------

Up and running. Check 04_BINNING/work_files/concoct_out/log.txt for progress
/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/Bio/Seq.py:341: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)

```

here is the log file. 
```
2018-04-21 20:23:55,643:INFO:root:Results created at ..
/04_BINNING/work_files/concoct_out
2018-04-21 20:33:48,833:INFO:root:Successfully loaded composition data.
2018-04-21 20:33:52,034:INFO:root:Successfully loaded coverage data.
2018-04-21 20:34:02,290:INFO:root:Performed PCA, resulted in 36 dimensions
2018-04-21 20:36:51,900:INFO:root:Wrote original filtered data file.
2018-04-21 20:37:36,764:INFO:root:Wrote PCA transformed file.
2018-04-21 20:37:36,781:INFO:root:Wrote PCA components file.
2018-04-21 20:37:36,781:INFO:root:PCA transformed data.
2018-04-21 20:37:36,781:INFO:root:Will call vbgmm with parameters: ./, 400, 1000
```


Thanks a lot!

**Comment by ursky** [comment]
Great! Yeah, I’ve seen this error in CheckM but I don’t think it has an effect on the output. I wouldn’t worry about it.

As for CONCOCT, yes it’s notoriously slow, since it only uses one thread (it looks like it’s using 10, but those are actually run “replicates”). Given how many bins you have from the other two binners, I’m assuming you have a large data set, so it’s possible that CONCOCT will take many days... even more annoyingly, there is no way of knowing how long you have left.

Fortunately, concoct is usually outperformed by metabat and maxbin, unless you have soil-like data with high strain heterogeneity (have a look at the Metawrap paper for benchmarks). If you have limited time available, I would skip concoct. If you’d like you can deploy another binner instead, or just proceed with two binners (binning refiner still works pretty well with two). If you still want to have three binners, Metabat1 is a good alternative, as it’s super fast and the input files are the same as for metabat2. I’ll eventually add a metabat1 option for metawrap, but for now you can just hum it manually, or go into the metawrap code and change metabat2 to metabat1.


On Apr 22, 2018, at 3:09 PM, Thexiyang <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the response. The output folders look all fine: bins, lineage.m, storage in .checkm folder and also there is .stats folder. They are all with reasonable data there for both maxbin2 and metabat2. It seems that it worked out. I am following the whole pipeline and probably can give you further feedback on this during the refine step where checkm will be used more often.

Ps: how slow is the concoct binning process? It has been like this since 20 hours ago and there is nothing changes for the log file since the starting point. Should I just kill it?

------------------------------------------------------------------------------------------------------------------------
-----                            Starting binning with CONCOCT. This may take a while...                           -----
------------------------------------------------------------------------------------------------------------------------

Up and running. Check 04_BINNING/work_files/concoct_out/log.txt for progress
/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/Bio/Seq.py:341: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)



here is the log file.

2018-04-21 20:23:55,643:INFO:root:Results created at ..
/04_BINNING/work_files/concoct_out
2018-04-21 20:33:48,833:INFO:root:Successfully loaded composition data.
2018-04-21 20:33:52,034:INFO:root:Successfully loaded coverage data.
2018-04-21 20:34:02,290:INFO:root:Performed PCA, resulted in 36 dimensions
2018-04-21 20:36:51,900:INFO:root:Wrote original filtered data file.
2018-04-21 20:37:36,764:INFO:root:Wrote PCA transformed file.
2018-04-21 20:37:36,781:INFO:root:Wrote PCA components file.
2018-04-21 20:37:36,781:INFO:root:PCA transformed data.
2018-04-21 20:37:36,781:INFO:root:Will call vbgmm with parameters: ./, 400, 1000


Thanks a lot!

**Comment by Thexiyang** [comment]
Thanks! I will the concoct process and manually run with metabat1.

**Comment by ursky** [comment]
Ok! I recommend using the —veryspecific option, given the complexity of your data. The feel free to use the depth file from the metabat2 run!


On Apr 22, 2018, at 4:56 PM, Thexiyang <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! I will the concoct process and manually run with metabat1.
