### ISSUE TITLE
Error with refinment

### ISSUE THREAD

**Issue by bestweicheng** [bxlab/metaWRAP#244]
------------------------------------------------------------------------------------------------------------------------
-----              There are 53 'good' bins found in binsABC! (>70% completion and <10% contamination)             -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                     Running CheckM on binsAB.checkm bins                                     -----
------------------------------------------------------------------------------------------------------------------------

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/home/zwc/miniconda3/envs/metawrap/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/home/zwc/miniconda3/envs/metawrap/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/home/zwc/miniconda3/envs/metawrap/lib/python2.7/site-packages/checkm/main.py", line 110, in tree
    binFiles = self.binFiles(options.bin_folder, options.extension)
  File "/home/zwc/miniconda3/envs/metawrap/lib/python2.7/site-packages/checkm/main.py", line 87, in binFiles
    all_files = os.listdir(binFolder)
OSError: [Errno 2] No such file or directory: 'binsAB.checkm'

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
********************************************

**Comment by ursky** [comment]
This means the union of the two bin sets did not yield any valid bins. Probably because one of them had very few bins.
