### ISSUE TITLE
CheckM bin_refinement - not such file or directory error

### ISSUE THREAD

**Issue by joaopcpg** [bxlab/metaWRAP#265]
Hi, I'm running into an issue when using the bin_refinement tool with 3 directory inputs and got this error:

```
------------------------------------------------------------------------------------------------------------------------
-----                                     Running CheckM on binsAB.checkm bins                                     -----
------------------------------------------------------------------------------------------------------------------------


*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************


Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 110, in tree
    binFiles = self.binFiles(options.bin_folder, options.extension)
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 87, in binFiles
    all_files = os.listdir(binFolder)
OSError: [Errno 2] No such file or directory: 'binsAB.checkm'

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************
```
Any idea how I could resolve this?

The entire output: 
```

------------------------------------------------------------------------------------------------------------------------
-----            There is 40 RAM and 5 threads available, and each pplacer thread uses >40GB, so I will            -----
-----                                          use 1 threads for pplacer                                           -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                                BEGIN PIPELINE!                                               #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                              setting up output folder and copything over bins...                             -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****             Warning: /home/joaopedro-coelho/Softwares/checkm/teste/BIN_REFINEMENT already exists.            *****
*****                                             Attempting to clean.                                             *****
************************************************************************************************************************

rm: cannot remove '/home/joaopedro-coelho/Softwares/checkm/teste/BIN_REFINEMENT/bin.*': No such file or directory

------------------------------------------------------------------------------------------------------------------------
-----                                          there are 48 bins in binsA                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                          there are 40 bins in binsB                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                          there are 101 bins in binsC                                         -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                             There are 3 bin sets!                                            -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                              Fix contig naming by removing special characters...                             -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                             BEGIN BIN REFINEMENT                                             #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----              There are three bin folders, so there 4 ways we can refine the bins (A+B, B+C, A+C,             -----
-----                                    A+B+C). Will try all four in parallel!                                    -----
------------------------------------------------------------------------------------------------------------------------

Specified 3 input bin sets: -1 binsA -2 binsB -3 binsC
Specified 2 input bin sets: -1 binsA -2 binsB
Specified 2 input bin sets: -1 binsC -2 binsB
Specified 2 input bin sets: -1 binsA -2 binsC
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsC bins
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsB bins
Add folder/bin name to contig name for binsC bins
Add folder/bin name to contig name for binsB bins
Combine all bins together
Add folder/bin name to contig name for binsC bins
The number of refined bins: 82
Exporting refined bins...
Add folder/bin name to contig name for binsB bins
Combine all bins together
Combine all bins together
Combine all bins together
The number of refined bins: 78
The number of refined bins: 78
Exporting refined bins...
Exporting refined bins...
The number of refined bins: 65
Exporting refined bins...
Extracting refined bin: Refined_65.fasta
Deleting temporary files

All done!
Extracting refined bin: Refined_82.fasta
Deleting temporary files

All done!
Extracting refined bin: Refined_78.fasta
Deleting temporary files

All done!
Extracting refined bin: Refined_78.fasta
Deleting temporary files

All done!

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 82 refined bins in binsAB                                     -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 78 refined bins in binsBC                                     -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 78 refined bins in binsAC                                     -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                     there are 65 refined bins in binsABC                                     -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                     Bin refinement finished successfully!                                    -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                            fixing bin naming to .fa convention for consistancy...                            -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                      RUNNING CHECKM ON ALL SETS OF BINS                                      #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------


*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 48 bins with 5 threads:
    Finished processing 48 of 48 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 48 bins with 5 threads:
    Finished processing 48 of 48 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 48 of 48 (100.00%) bins.
  Extracting 43 HMMs with 5 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 5 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 48 bins into the genome tree with pplacer (be patient).

  { Current stage: 0:14:30.027 || Total: 0:14:30.027 }
*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 48 of 48 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 48 of 48 (100.00%) bins (current: bin.45).

  Marker set written to: binsA.checkm/lineage.ms

  { Current stage: 0:00:07.746 || Total: 0:14:37.773 }

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 48 bins with 5 threads:
    Finished processing 48 of 48 (100.00%) bins.
  Saving HMM info to file.

  { Current stage: 0:06:17.577 || Total: 0:20:55.351 }

  Parsing HMM hits to marker genes:
    Finished parsing hits for 48 of 48 (100.00%) bins.
  Aligning marker genes with multiple hits in a single bin:
    Finished processing 48 of 48 (100.00%) bins.

  { Current stage: 0:00:30.109 || Total: 0:21:25.460 }

  Calculating genome statistics for 48 bins with 5 threads:
    Finished processing 48 of 48 (100.00%) bins.

  { Current stage: 0:00:03.943 || Total: 0:21:29.404 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************
Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 48 of 48 (100.00%) bins.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  { Current stage: 0:00:11.316 || Total: 0:21:40.721 }

------------------------------------------------------------------------------------------------------------------------
-----               There are 13 'good' bins found in binsA! (>70% completion and <5% contamination)               -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsAB bins                                        -----
------------------------------------------------------------------------------------------------------------------------


*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 82 bins with 5 threads:
    Finished processing 82 of 82 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 82 bins with 5 threads:
    Finished processing 82 of 82 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 82 of 82 (100.00%) bins.
  Extracting 43 HMMs with 5 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 5 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 82 bins into the genome tree with pplacer (be patient).

  { Current stage: 0:10:35.620 || Total: 0:10:35.620 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 82 of 82 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 82 of 82 (100.00%) bins (current: Refined_77).

  Marker set written to: binsAB.checkm/lineage.ms

  { Current stage: 0:00:10.111 || Total: 0:10:45.732 }

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 82 bins with 5 threads:
    Finished processing 82 of 82 (100.00%) bins.
  Saving HMM info to file.

  { Current stage: 0:05:08.500 || Total: 0:15:54.232 }

  Parsing HMM hits to marker genes:
    Finished parsing hits for 82 of 82 (100.00%) bins.
  Aligning marker genes with multiple hits in a single bin:
    Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:20.449 || Total: 0:16:14.682 }

  Calculating genome statistics for 82 bins with 5 threads:
    Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:01.260 || Total: 0:16:15.943 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 82 of 82 (100.00%) bins.
Aligning marker genes with multiple hits in a single bin:
    Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:20.449 || Total: 0:16:14.682 }

  Calculating genome statistics for 82 bins with 5 threads:
    Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:01.260 || Total: 0:16:15.943 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 82 of 82 (100.00%) bins.
Aligning marker genes with multiple hits in a single bin:
    Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:20.449 || Total: 0:16:14.682 }

  Calculating genome statistics for 82 bins with 5 threads:
    Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:01.260 || Total: 0:16:15.943 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 82 of 82 (100.00%) bins.
Aligning marker genes with multiple hits in a single bin:
 Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:20.449 || Total: 0:16:14.682 }

  Calculating genome statistics for 82 bins with 5 threads:
    Finished processing 82 of 82 (100.00%) bins.

  { Current stage: 0:00:01.260 || Total: 0:16:15.943 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 82 of 82 (100.00%) bins.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  { Current stage: 0:00:17.028 || Total: 0:16:32.971 }

------------------------------------------------------------------------------------------------------------------------
-----               There are 12 'good' bins found in binsAB! (>70% completion and <5% contamination)              -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                        Running CheckM on binsABC bins                                        -----
------------------------------------------------------------------------------------------------------------------------


*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 65 bins with 5 threads:
    Finished processing 65 of 65 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 65 bins with 5 threads:
    Finished processing 65 of 65 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 65 of 65 (100.00%) bins.
  Extracting 43 HMMs with 5 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 5 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 65 bins into the genome tree with pplacer (be patient).

  { Current stage: 0:09:22.368 || Total: 0:09:22.368 }
*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 65 of 65 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 65 of 65 (100.00%) bins (current: Refined_17).

  Marker set written to: binsABC.checkm/lineage.ms

  { Current stage: 0:00:07.613 || Total: 0:09:29.982 }

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 65 bins with 5 threads:
    Finished processing 65 of 65 (100.00%) bins.
  Saving HMM info to file.

  { Current stage: 0:04:01.831 || Total: 0:13:31.813 }

  Parsing HMM hits to marker genes:
    Finished parsing hits for 65 of 65 (100.00%) bins.
  Aligning marker genes with multiple hits in a single bin:
    Finished processing 65 of 65 (100.00%) bins.

  { Current stage: 0:00:08.686 || Total: 0:13:40.499 }

  Calculating genome statistics for 65 bins with 5 threads:
    Finished processing 65 of 65 (100.00%) bins.

  { Current stage: 0:00:00.725 || Total: 0:13:41.225 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.
 Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 65 of 65 (100.00%) bins.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  { Current stage: 0:00:09.506 || Total: 0:13:50.731 }

------------------------------------------------------------------------------------------------------------------------
-----              There are 11 'good' bins found in binsABC! (>70% completion and <5% contamination)              -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                     Running CheckM on binsAB.checkm bins                                     -----
------------------------------------------------------------------------------------------------------------------------


*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************


Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 110, in tree
    binFiles = self.binFiles(options.bin_folder, options.extension)
  File "/home/joaopedro-coelho/anaconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 87, in binFiles
    all_files = os.listdir(binFolder)
OSError: [Errno 2] No such file or directory: 'binsAB.checkm'

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************


real    67m57.426s
user    150m10.969s
sys     7m54.159s
```
I didn't put the part of the Tabulating Genome Statistics classification because I thought there was no need

The imput:

```
metawrap bin_refinement -o \
/home/joaopedro-coelho/Softwares/checkm/teste/BIN_REFINEMENT \
-t 10 \
-A /home/joaopedro-coelho/Softwares/checkm/teste/INITIAL_BINNING/metabat2_bins \
-B /home/joaopedro-coelho/Softwares/checkm/teste/INITIAL_BINNING/maxbin2_bins \
-C /home/joaopedro-coelho/Softwares/checkm/teste/INITIAL_BINNING/concoct_bins \
-c 70 -x 5
```
Thanks in advance!

**Comment by ganiatgithub** [comment]
Hi,

I have the same issue here, anytips?

Thanks!

**Comment by ursky** [comment]
The union of the two bin sets likely did not result in any bins.

**Comment by Mamingjie543** [comment]
Hi
I also encountered the same problem, do you have a solution.
