### ISSUE TITLE
checkm error 22

### ISSUE THREAD

**Issue by newmacuser** [bxlab/metaWRAP#267]
Hello,

I had metawrap run on my local machine and had an error occurred during refinement process. It seems like an argument error related with CheckM.
The error part looks like the following:

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 29 bins with 12 threads:
Process SyncManager-1:
Traceback (most recent call last):
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

Unexpected error: <type 'exceptions.EOFError'>
Traceback (most recent call last):
  File "/home/ytm/miniconda3/envs/metawrap-env/bin/checkm", line 711, in <module>
    checkmParser.parseOptions(args)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1252, in parseOptions
    self.tree(options)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 134, in tree
    options.bCalledGenes)
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 67, in find
    binIdToModels = mp.Manager().dict()
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/home/ytm/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************

I had searched Google on this type of error 22 but didn't get anything workable. 
Hope someone can share any thoughts on this error.

Best
TY

**Comment by newmacuser** [comment]
Hi, 

I finally figured out this error is because of a hard disk issue. I loaded my data on an external drive while the connection was somehow not stable. Once I copied all files to internal SSD, all error solved.
