### ISSUE TITLE
error in bin_refinement

### ISSUE THREAD

**Issue by eertekin** [bxlab/metaWRAP#28]
When I run : metawrap /home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/bin/metawrap-modules/bin_refinement -o /home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref -A /home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binning/concoct_bins -B /home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binning/maxbin2_bins -C /home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binning/metabat2_bins

I get the error:
```
########################################################################################################################
#####                                                BEGIN PIPELINE!                                               #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                              setting up output folder and copything over bins...                             -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                          there are 13 bins in binsA                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                           there are 4 bins in binsB                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                           there are 5 bins in binsC                                          -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                             There are 3 bin sets!                                            -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                              Fix contig naming by removing special characters...                             -----
------------------------------------------------------------------------------------------------------------------------

/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.0.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.10.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.11.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.1.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.2.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.3.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.4.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.5.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.6.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.7.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.8.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/bin.9.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsA/unbinned.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsB/bin.0.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsB/bin.1.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsB/bin.2.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsB/bin.3.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsC/bin.1.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsC/bin.2.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsC/bin.3.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsC/bin.4.fa
/home-2/eerteki2@jhu.edu/scratch/Binning/BAC_metagenomes_binning/AS_binref/binsC/bin.unbinned.fa

########################################################################################################################
#####                                             BEGIN BIN REFINEMENT                                             #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----              There are three bin folders, so there 4 ways we can refine the bins (A+B, B+C, A+C,             -----
-----                                    A+B+C). Will try all four in parallel!                                    -----
------------------------------------------------------------------------------------------------------------------------

Specified 2 input bin sets: -1 binsA -2 binsB
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsB bins
Combine all bins together
The number of refined bins: 4
Exporting refined bins...
Extracting refined bin: Refined_4.fasta
Deleting temporary files

All done!
Specified 2 input bin sets: -1 binsA -2 binsC
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsC bins
Combine all bins together
The number of refined bins: 6
Exporting refined bins...
Extracting refined bin: Refined_6.fasta
Deleting temporary files

All done!
Specified 2 input bin sets: -1 binsC -2 binsB
Add folder/bin name to contig name for binsC bins
Add folder/bin name to contig name for binsB bins
Combine all bins together
The number of refined bins: 6
Exporting refined bins...
Extracting refined bin: Refined_6.fasta
Deleting temporary files

All done!
Specified 3 input bin sets: -1 binsA -2 binsB -3 binsC
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsB bins
Add folder/bin name to contig name for binsC bins
Combine all bins together
The number of refined bins: 5
Exporting refined bins...
Extracting refined bin: Refined_5.fasta
Deleting temporary files

All done!

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 4 refined bins in binsAB                                      -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 6 refined bins in binsBC                                      -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 6 refined bins in binsAC                                      -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                      there are 5 refined bins in binsABC                                     -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                                     Bin refinement finished successfully!                                    -----
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-----                            fixing bin naming to .fa convention for consistancy...                            -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                      RUNNING CHECKM ON ALL SETS OF BINS                                      #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 13 bins with 1 threads:
Process Process-2:ssing 0 of 13 (0.00%) bins.
Traceback (most recent call last):
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home-2/eerteki2@jhu.edu/scratch/Database/CheckM/hmms/phylo.hmm'

  Saving HMM info to file.

  Calculating genome statistics for 13 bins with 1 threads:
    Finished processing 13 of 13 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1244, in parseOptions
    self.tree(options)
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 104, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/home-2/eerteki2@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1205, in parseOptions
    if options.bVerbose:
AttributeError: 'Namespace' object has no attribute 'bVerbose'

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************


real	0m48.700s
user	0m19.135s
sys	0m4.592s
```

**Comment by ursky** [comment]
Did you install the CheckM database and specify its location? Updating metaWRAP might have erased your information in `config-metawrap`.

**Comment by eertekin** [comment]
Oops, yes that was the problem. Now its running. Thanks!
