### ISSUE TITLE
metasapdes error

### ISSUE THREAD

**Issue by hjh-go** [bxlab/metaWRAP#299]
$ metawrap assembly  -1  CLEAN_READS/ALL_READS_1.fastq  -2 CLEAN_READS/ALL_READS_2.fastq  -o ASSEMBLYOUT
metawrap assembly -1 CLEAN_READS/ALL_READS_1.fastq -2 CLEAN_READS/ALL_READS_2.fastq -o ASSEMBLYOUT

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----            assembling CLEAN_READS/ALL_READS_1.fastq and CLEAN_READS/ALL_READS_2.fastq with megahit           -----
------------------------------------------------------------------------------------------------------------------------

Cannot find ASSEMBLYOUT/megahit/opts.txt
Please check whether the output directory is correctly set by "-o"
Now switching to normal mode.
MEGAHIT v1.1.3
--- [Tue Sep 22 10:48:56 2020] Start assembly. Number of CPU threads 1 ---
--- [Tue Sep 22 10:48:56 2020] Available memory: 153535606784, used: 24000000000

************************************************************************************************************************
*****                         Something went wrong with reassembling with Megahit. Exiting.                        *****
************************************************************************************************************************

real    0m3.775s
user    0m0.469s
sys     0m1.547s

**Comment by ursky** [comment]
Did you try running the command manually? Looks like something got interrupted.

**Comment by hjh-go** [comment]
> Did you try running the command manually? Looks like something got interrupted.

(metawrap) huang@DESKTOP-QLIST7H:/mnt/g/meta$ metawrap assembly -1 CLEAN_READS/ALL_READS_1.fastq -2 CLEAN_READS/ALL_READS_2.fastq  -t 12 --metaspades -o ASSEMBLYOUT
metawrap assembly -1 CLEAN_READS/ALL_READS_1.fastq -2 CLEAN_READS/ALL_READS_2.fastq -t 12 --metaspades -o ASSEMBLYOUT
Warning: ASSEMBLYOUT already exists.

########################################################################################################################
#####                                          ASSEMBLING WITH METASPADES                                          #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----           Using reads CLEAN_READS/ALL_READS_1.fastq and CLEAN_READS/ALL_READS_2.fastq for assembly,          -----
------------------------------------------------------------------------------------------------------------------------

Command line: /home/huang/miniconda2/envs/metawrap/bin/metaspades.py    --tmp-dir       /mnt/g/meta/ASSEMBLYOUT/metaspades.tmp  -t      12      -m      24      -o      /mnt/g/meta/ASSEMBLYOUT/metaspades      -1      /mnt/g/meta/CLEAN_READS/ALL_READS_1.fastq       -2      /mnt/g/meta/CLEAN_READS/ALL_READS_2.fastq

System information:
  SPAdes version: 3.13.0
  Python version: 2.7.15
  OS: Linux-4.4.0-18362-Microsoft-x86_64-with-debian-bullseye-sid

Output dir: /mnt/g/meta/ASSEMBLYOUT/metaspades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/mnt/g/meta/CLEAN_READS/ALL_READS_1.fastq']
      right reads: ['/mnt/g/meta/CLEAN_READS/ALL_READS_2.fastq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /mnt/g/meta/ASSEMBLYOUT/metaspades.tmp
  Threads: 12
  Memory limit (in Gb): 24


======= SPAdes pipeline started. Log can be found here: /mnt/g/meta/ASSEMBLYOUT/metaspades/spades.log


===== Read error correction started.

[Errno 1] Operation not permitted: '/mnt/g/meta/ASSEMBLYOUT/metaspades/corrected/configs/config.info'
Traceback (most recent call last):
  File "/home/huang/miniconda2/envs/metawrap/bin/metaspades.py", line 790, in main
    ext_python_modules_home, only_compressing_is_needed, log)
  File "/home/huang/miniconda2/envs/metawrap/share/spades-3.13.0-0/share/spades/spades_pipeline/hammer_logic.py", line 131, in run_hammer
    dir_util.copy_tree(os.path.join(configs_dir, "hammer"), dst_configs, preserve_times=False)
  File "/home/huang/miniconda2/envs/metawrap/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/home/huang/miniconda2/envs/metawrap/lib/python2.7/distutils/file_util.py", line 165, in copy_file
    os.chmod(dst, S_IMODE(st[ST_MODE]))
OSError: [Errno 1] Operation not permitted: '/mnt/g/meta/ASSEMBLYOUT/metaspades/corrected/configs/config.info'


== Error ==  exception caught: <type 'exceptions.OSError'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

************************************************************************************************************************
*****                            Something went wrong with metaSPAdes assembly. Exiting.                           *****
************************************************************************************************************************


real    0m4.439s
user    0m0.234s
sys     0m0.844s

**Comment by URIUPF** [comment]
were you able to solve it? I'm having the same error now

**Comment by MZNOTE** [comment]
我是建航，你的邮件已经收到，辛苦了！

**Comment by UMassDVR** [comment]
I have the same error. Has anyone solved this?

Cannot find ASSEMBLY/megahit/opts.txt
Please check whether the output directory is correctly set by "-o"

**Comment by MZNOTE** [comment]
我是建航，你的邮件已经收到，辛苦了！
