### ISSUE TITLE
Error quant_bins module

### ISSUE THREAD

**Issue by palomo11** [bxlab/metaWRAP#3]
Hi,

I have run quant_bins but it has stopped with the following error:
```
`Starting in: /home/projects/env_10000/people/alpal/WaterWorks/F17FTSEUET0039_BACggoR/Clean/Alex_1/IDBA_all_TM_meta/all_merged_TM_paired_IDBA_OK/metaWRAP/binning_all_OK/bin_refinement/quantification/alignment_files
Loading counts from: ./CGAGGCTGTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./TACGCTGCTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./GTAGAGGATCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./CGGAGCCTTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./ATGCGCAGTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./AAGAGGCATCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./AGGCAGAAAGAGGATA_merged_TM_paired.quant quant.sf
Loading counts from: ./CGTACTAGAGAGGATA_merged_TM_paired.quant quant.sf
Loading counts from: ./ATCTCAGGTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./TAGCGCTCTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./AGGCAGAATCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./GCTCATGATCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./GGAGCTACTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./CGAGGCTGCTAGTCGA_merged_TM_paired.quant quant.sf
Loading counts from: ./ACTCGCTATCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./GGACTCCTAGAGGATA_merged_TM_paired.quant quant.sf
Loading counts from: ./TCCTGAGCAGAGGATA_merged_TM_paired.quant quant.sf
Loading counts from: ./CTCTCTACCTAGTCGA_merged_TM_paired.quant quant.sf
Loading counts from: ./TAGGCATGTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./GCTACGCTTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./GGACTCCTTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./CTCTCTACTCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./GCGTAGTATCGCATAA_merged_TM_paired.quant quant.sf
Loading counts from: ./TAGGCATGAGAGGATA_merged_TM_paired.quant quant.sf
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/metawrap-env/bin/metawrap-scripts/split_salmon_out_into_bins.py", line 27, in <module>
    bin_abundances[bin]["total_len"]+=int(line.split("\t")[0].split("_")[3])
IndexError: list index out of range
```

It finished like this:
```
########################################################################################################################
#####                                   EXTRACTING AVERAGE ABUNDANCE OF EACH BIN                                   #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                            There were 24 samples detected. Making abundance table!                           -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
                   something went wrong with making summary abundance table. Exiting...                     
```

This is how the output folder looks:
```
61 Jan 15 12:15 all_bin_contigs
1536 Jan 15 13:20 quant_files
1368 Jan 15 13:20 alignment_files
0 Jan 15 13:20 abundance_table.tab
```

Each quant.sf looks like:
```
(metawrap-env) head quant.sf 
Name	Length	EffectiveLength	TPM	NumReads
contig-1	420936	420800.156	183.796403	109528.269851
contig-2	412056	411920.156	3.191064	1861.495250
contig-3	406383	406247.156	65.965626	37950.836252
contig-4	389993	389857.156	5.964740	3293.141174
contig-5	382469	382333.156	3.212324	1739.300499
contig-6	338179	338043.156	3.197438	1530.691453
contig-7	326651	326515.156	5.777906	2671.696687
contig-8	316073	315937.156	6.080464	2720.512609
contig-9	310613	310477.156	5.813615	2556.167111
```

Any idea about what is going on?

Thanks in advance.

**Comment by ursky** [comment]
Thanks for this! My code was apparently not universal for all contig naming conventions. This bug has been fixed in `metaWRAP v=0.65`. I also made the module slightly faster as well :)

I also changed some metaWRAP's dependencies so that it hopefully won't butt heads with your cluster's GCC, so I encourage you to remake the metawrap environment.

**Comment by palomo11** [comment]
It works fine after installing the new version. Thanks!

**Comment by palomo11** [comment]
I have got an error while running the quant_bins module:

300 Feb  7 20:09 assembly_index
1536 Feb  7 20:22 quant_files
1368 Feb  7 20:22 alignment_files
0 Feb  7 20:22 abundance_table.tab

The error:
```
Loading counts from: ./A1.quant quant.sf
Loading counts from: ./A2.quant quant.sf
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/metawrap-env/bin/metawrap-scripts/split_salmon_out_into_bins.py", line 39, in <module>
    bin_abundances[bin]["total_len"]+=contig_lengths[line.split("\t")[0]]
KeyError: 'NTT_9-2948'
```

one of the quant.sf files looks like:
```
Name	Length	EffectiveLength	TPM	NumReads
contig-1673	33461	33276.054	8.732845	55.526894
contig-2011	30366	30181.054	42.073555	242.638354
....
....
....
NTT_9-2527	1225	1040.054	934.421424	185.701066
NTT_9-2625	1190	1005.054	1201.641601	230.770382
NTT_9-2661	1178	993.054	1712.753167	325.000000
NTT_9-2814	1132	947.054	1992.883028	360.638644
NTT_9-2828	1128	943.054	1337.801299	241.070398
NTT_9-2947	614	431.962	2231.053931	184.149826
NTT_9-2948	591	409.974	957.389568	75.000000
```

Thanks in advance.

**Comment by ursky** [comment]
I was able to replicate this error, which came up when the contig names had a space in them. This bug has been fixed in metaWRAP v0.7.3!

**Comment by palomo11** [comment]
I got a new error:

The output folder looks like:

 300 Feb 12 13:40 assembly_index
 1536 Feb 12 13:53 quant_files
 1368 Feb 12 13:53 alignment_files
 1215 Feb 12 13:53 abundance_table.tab
 1043 Feb 12 13:53 sample_read_count.tab

So abundance file is produced but it just appears the abundance of 1 bin for each sample even if I have more bins...

```
Traceback (most recent call last):
  File "/home/people/name/.conda/envs/metawrap-env/bin/metawrap-scripts/make_heatmap.py", line 63, in <module>
    g = sns.clustermap(z, figsize=(14,8), col_colors=lut, col_cluster=True)
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 1301, in clustermap
    **kwargs)
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 1131, in plot
    row_linkage=row_linkage, col_linkage=col_linkage)
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 1024, in plot_dendrograms
    ax=self.ax_row_dendrogram, rotate=True, linkage=row_linkage)
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 746, in dendrogram
    label=label, rotate=rotate)
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 564, in __init__
    self.linkage = self.calculated_linkage
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 628, in calculated_linkage
    return self._calculate_linkage_scipy()
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/seaborn/matrix.py", line 603, in _calculate_linkage_scipy
    metric=self.metric)
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 716, in linkage
    n = int(distance.num_obs_y(y))
  File "/home/people/name/.conda/envs/metawrap-env/lib/python2.7/site-packages/scipy/spatial/distance.py", line 2051, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```

I'm not sure if it's because the same conting name now appears multiple times:
```
Name    Length  EffectiveLength TPM     NumReads
Scaffold_1      88598   88470.903       535.838437      5393.275301
Scaffold_2      32609   32481.903       601.849309      2224.065108
.......
Scaffold_1      18465   18337.903       675.809016      1409.911708
Scaffold_2      89713   89585.903       557.672582      5683.779679
```

**Comment by ursky** [comment]
This is strange. Can you please give me the full contents of `abundance_table.tab` and `sample_read_count.tab`? Thank you for your patience...

**Comment by palomo11** [comment]
```
(metawrap-env) cat abundance_table.tab
Genomic bins	Sample1	Sample2	Sample3	Sample4	Sample5	Sample6	Sample7	Sample8	Sample9	Sample10	Sample11	Sample12	Sample13	Sample14	Sample15	Sample16	Sample17	Sample18	Sample19	Sample20	Sample21	Sample22	Sample23	Sample24
Bin1	1137.650719	1069.32491	916.5846534	1150.069762	1041.65058	872.6087868	1170.375271	893.0761527	1046.031431	1096.165997	1187.823918	1134.793664	1032.655892	1172.95005	1127.612158	1216.887463	1054.915047	919.5064942	867.0684717	1045.114386	1126.458803	1189.516783	1073.855808	1269.363726
```
```
(metawrap-env) cat sample_read_count.tab
#samples	reads
Sample1	2337758
Sample2	8769190
Sample3	9427631
Sample4	12051050
Sample5	9008958
Sample6	10216791
Sample7	11886730
Sample8	13492147
Sample9	13004268
Sample10	15073835
Sample11	15569155
Sample12	17471447
Sample13	16161964
Sample14	16507114
Sample15	15108992
Sample16	17941744
Sample17	17980570
Sample18	10500764
Sample19	12715521
Sample20	13644734
Sample21	14894712
Sample22	15397351
Sample23	16739443
Sample24	16244189
```

**Comment by ursky** [comment]
Just to clarify - the bins files (-b option) that you are quantifying contain the exact same contigs that are in the assembly file (-a option)? 

It looks like the contig names between some of the input files are not consistent. To diagnose, I will need to see the contig naming convention in the following files:
1. One out your .quant files: `cat output_folder/quant_files/Sample1.quant.counts | sort -k1 | head` (or any file in the `quant_files` output directory.
2. Your assembly input (-a): `grep ">" assembly_file.fa | sort | head`
3. A few of your bin files: `for i in bin_folder/*; do grep ">" $i | sort | head; done`, where bin_folder is the directory with bin files. You can give the output for just the first 3 bins if you have too many.

**Comment by palomo11** [comment]
Hi,

I have reinstall metawrap from scratch and try it again.

Now the error is:

```
Loading counts from: ./Sample23.quant quant.sf
Loading counts from: ./Sample24.quant quant.sf
Traceback (most recent call last):
  File "/home/people/name/.conda/envs/metawrap-env/bin/metawrap-scripts/split_salmon_out_into_bins.py", line 39, in <module>
    bin_abundances[bin]["total_len"]+=contig_lengths[line.split("\t")[0]]
KeyError: 'Bin_9_46'
```
And the abundance.table.tab is not produced....

Here I copy you the results of the three commands you suggested me to run:

```
(metawrap-env) [alpal@computerome02 quant_files]$ cat Sample1.quant.counts | sort -k1 | head 
300_Bin1_1	169.776569
300_Bin1_10	226.962823
300_Bin1_11	162.273498
300_Bin1_12	198.6778
300_Bin1_13	184.598378
300_Bin1_14	201.538054
300_Bin1_15	253.642709
300_Bin1_16	158.982662
300_Bin1_17	194.552904
300_Bin1_18	296.046523
```
```
(metawrap-env) $ grep ">" assembly.fa | sort | head
>300_Bin1_1
>300_Bin1_10
>300_Bin1_11
>300_Bin1_12
>300_Bin1_13
>300_Bin1_14
>300_Bin1_15
>300_Bin1_16
>300_Bin1_17
>300_Bin1_18
```
```
for i in bins_dir/*; do grep ">" $i | sort | head; done
>300_Bin1_1
>300_Bin1_10
>300_Bin1_11
>300_Bin1_12
>300_Bin1_13
>300_Bin1_14
>300_Bin1_15
>300_Bin1_16
>300_Bin1_17
>300_Bin1_18
>bin.86_1
>bin.86_10
>bin.86_100
>bin.86_101
>bin.86_11
>bin.86_12
>bin.86_13
>bin.86_14
>bin.86_15
>bin.86_16
>Bin_9_1
>Bin_9_10
>Bin_9_11
>Bin_9_12
>Bin_9_13
>Bin_9_14
>Bin_9_15
>Bin_9_16
>Bin_9_17
>Bin_9_18
```

With exactly the contig name that gave the error I have also searched for it in the different files:
```
(metawrap-env) $ grep "Bin_9_46" assembly.fa
>Bin_9_46
```
```
(metawrap-env) $ grep "Bin_9_46" bins_dir/*
bins_dir/Bin_9.fa:>Bin_9_46
```
```
(metawrap-env) [alpal@computerome02 quant_files]$ grep "Bin_9_46" Sample1.quant.counts
Bin_9_46	17.789214
```

**Comment by ursky** [comment]
I believe I was able to find the bug that was causing this, and updated it in metaWRAP v=0.7.4. However, I don't want to celebrate yet until I you get it working on your end. Let me know!

**Comment by palomo11** [comment]
It works! Thanks!

**Comment by ursky** [comment]
Fantastic! For your information, I am changing metaWRAP's name in anaconda from `metawrap-binning` to `metawrap-mg` after this version. MetaWRAP does much more than binning.

**Comment by rotoscan** [comment]
Hello, I also had an eroror with version 0.9.5

Please check my .err output file

Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
index ["/data/msb/tools/metawrap/testing_dir/EVE_test/QUANT_bins/assembly_index"] did not previously exist  . . . creating it
[2018-09-21 10:29:39.726] [jLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers
counted k-mers for 20000 transcriptsElapsed time: 2.69846s

Replaced 312511 non-ATCG nucleotides
Clipped poly-A tails from 3 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 0.00525741s
Writing sequence data to file . . . done
Elapsed time: 0.0382343s
[info] Building 32-bit suffix array (length of generalized text is 63290070)
Building suffix array . . . success
saving to disk . . . done
Elapsed time: 0.0761879s
done
Elapsed time: 5.23032s
processed 30000000 positions
processed 61000000 positions
processed 63000000 positions
khash had 62550593 keys
saving hash to disk . . . done
Elapsed time: 3.0806s
[2018-09-21 10:30:36.673] [jLog] [info] done building index
Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
### salmon (mapping-based) v0.9.1
### [ program ] => salmon 
### [ command ] => quant 
### [ index ] => { /data/msb/tools/metawrap/testing_dir/EVE_test/QUANT_bins/assembly_index }
### [ libType ] => { IU }
### [ mates1 ] => { /data/msb/tools/metawrap/testing_dir/EVE_test/CLEAN_READS/ALL_READS_1.fastq }
### [ mates2 ] => { /data/msb/tools/metawrap/testing_dir/EVE_test/CLEAN_READS/ALL_READS_2.fastq }
### [ output ] => { /data/msb/tools/metawrap/testing_dir/EVE_test/QUANT_bins/alignment_files/ALL_READS.quant }
Logs will be written to /data/msb/tools/metawrap/testing_dir/EVE_test/QUANT_bins/alignment_files/ALL_READS.quant/logs
[2018-09-21 10:30:37.553] [jointLog] [info] parsing read library format
[2018-09-21 10:30:37.553] [jointLog] [info] There is 1 library.
[2018-09-21 10:30:37.595] [stderrLog] [info] Loading Suffix Array 
[2018-09-21 10:30:37.595] [jointLog] [info] Loading Quasi index
[2018-09-21 10:30:37.595] [jointLog] [info] Loading 32-bit quasi index
[2018-09-21 10:30:37.780] [stderrLog] [info] Loading Transcript Info 
[2018-09-21 10:30:37.841] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-09-21 10:30:37.857] [stderrLog] [info] There were 22449 set bits in the bit array
[2018-09-21 10:30:37.862] [stderrLog] [info] Computing transcript lengths
[2018-09-21 10:30:37.862] [stderrLog] [info] Waiting to finish loading hash
[2018-09-21 10:30:40.469] [stderrLog] [info] Done loading index




[2018-09-21 10:30:40.469] [jointLog] [info] done
processed 34000000 fragmentsointLog] [info] Index contained 22449 targets
hits: 14594372, hits per frag:  0.429918









[2018-09-21 10:31:08.855] [jointLog] [info] Computed 24614 rich equivalence classes for further processing
[2018-09-21 10:31:08.855] [jointLog] [info] Counted 14578433 total reads in the equivalence classes 
[2018-09-21 10:31:08.870] [jointLog] [warning] 5.83588% of fragments were shorter than the k used to build the index (31).
If this fraction is too large, consider re-building the index with a smaller k.
The minimum read size found was 20.


[2018-09-21 10:31:08.870] [jointLog] [info] Mapping rate = 42.8627%

[2018-09-21 10:31:08.870] [jointLog] [info] finished quantifyLibrary()
[2018-09-21 10:31:08.871] [jointLog] [info] Starting optimizer
[2018-09-21 10:31:08.929] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2018-09-21 10:31:08.931] [jointLog] [info] iteration = 0 | max rel diff. = 0.205239
[2018-09-21 10:31:08.957] [jointLog] [info] iteration = 100 | max rel diff. = 3.40165e-16
[2018-09-21 10:31:08.958] [jointLog] [info] Finished optimizer
[2018-09-21 10:31:08.958] [jointLog] [info] writing output 

Starting in: /gpfs1/data/msb/tools/metawrap/testing_dir/EVE_test/QUANT_bins/alignment_files
Loading counts from: ./ALL_READS.quant quant.sf
Traceback (most recent call last):
  File "/data/msb/tools/metawrap/metawrap_env/bin/metawrap-scripts/make_heatmap.py", line 74, in <module>
    draw_clustermap(df)
  File "/data/msb/tools/metawrap/metawrap_env/bin/metawrap-scripts/make_heatmap.py", line 56, in draw_clustermap
    g = sns.clustermap(df, figsize=(14,8), col_colors=lut, col_cluster=True, yticklabels=True, cmap="magma")
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/seaborn/matrix.py", line 1301, in clustermap
    **kwargs)
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/seaborn/matrix.py", line 1131, in plot
    row_linkage=row_linkage, col_linkage=col_linkage)
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/seaborn/matrix.py", line 1032, in plot_dendrograms
    axis=1, ax=self.ax_col_dendrogram, linkage=col_linkage)
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/seaborn/matrix.py", line 746, in dendrogram
    label=label, rotate=rotate)
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/seaborn/matrix.py", line 564, in __init__
    self.linkage = self.calculated_linkage
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/seaborn/matrix.py", line 628, in calculated_linkage
    return self._calculate_linkage_scipy()
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/seaborn/matrix.py", line 603, in _calculate_linkage_scipy
    metric=self.metric)
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 716, in linkage
    n = int(distance.num_obs_y(y))
  File "/data/msb/tools/metawrap/metawrap_env/lib/python2.7/site-packages/scipy/spatial/distance.py", line 2276, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.

real	1m48.914s
user	6m52.589s
sys	0m11.291s

**Comment by ursky** [comment]
Interesting... Can you provide the entire output of the module so I can get some context?

**Comment by ursky** [comment]
Thank you. What are the contents of `abundance_table.tab`?

**Comment by rotoscan** [comment]
```
$ more abundance_table.tab 
Genomic bins	ALL_READS
bin.10	53.5654101521
bin.12	142.430359404
bin.9	28.3896954994
bin.1	19.323651595
bin.4	43.0783674676
bin.2	25.9015445183
bin.5	69.8123963753
bin.11	42.188884418
bin.6	40.6758406012
bin.7	99.2588707933
bin.13	19.6026879689
bin.8	82.1517206263
bin.3	50.6797341763

```

**Comment by ursky** [comment]
I think you are fine then. The reason you get an error is because you cannot make a clustered heatmap with just one sample. Ill add documentation on this in the next version.

**Comment by rotoscan** [comment]
That makes a lot of sense. I was submitting only one library as input. I am testing now with the 3 samples and it is running. Thanks again!

**Comment by rotoscan** [comment]
Yeahp,

the problem was the input. Also, the input files have to have different names. I first tried with with files in different paths and with same names and it didn't work.
Looking good now though:

$ more abundance_table.tab 
Genomic bins	ERR011348_reads	ERR011347_reads	ERR011349_reads
bin.10	63.2995763491	80.1141572403	0.745527543183
bin.12	27.6447086494	49.4522084976	410.431994816
bin.9	36.0651686677	39.8873965702	0.150085654312
bin.1	10.1204482638	40.3466107775	1.07529147852
bin.4	43.7781098364	64.9233354676	5.77492102875
bin.2	21.6687147437	44.3219293627	2.29185325681
bin.5	69.3107947255	80.1267467922	44.3732262254
bin.11	68.1195663186	32.3021440865	21.423985044
bin.6	32.3853022143	69.5511490688	7.84672839857
bin.7	5.32634576051	20.409743568	323.937107902
bin.13	14.5992250362	33.0922439024	5.75527094687
bin.8	98.3386670249	112.292689318	1.21021275888
bin.3	38.3472039965	23.3477190086	100.892921691

Thanks!
