### ISSUE TITLE
CONCOCT error

### ISSUE THREAD

**Issue by alxsimon** [bxlab/metaWRAP#314]
Hi, binning with CONCOCT produced the following error.

I installed using the Best (manual) install guidelines. Also tried the bioconda install with the same error message.

```
Up and running. Check /data/ref_genomes/metawrap/INITIAL_BINNING/work_files/concoct_out/log.txt for progress
/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct/input.py:82: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  cov = p.read_table(cov_file, header=0, index_col=0)
Traceback (most recent call last):
File "/opt/miniconda3/envs/metawrap-env/bin/concoct", line 88, in <module>
	results = main(args)
File "/opt/miniconda3/envs/metawrap-env/bin/concoct", line 20, in main
	composition, cov, cov_range = load_data(args)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct/input.py", line 25, in load_data
	read_length = args.read_length
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct/input.py", line 92, in load_coverage
	axis='index')
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/ops.py", line 2030, in f
	level=level)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/ops.py", line 1917, in _combine_series_frame
	return self._combine_match_index(other, func, level=level)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/frame.py", line 5097, in _combine_match_index
	copy=False)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/frame.py", line 3792, in align
	broadcast_axis=broadcast_axis)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/generic.py", line 8428, in align
	fill_axis=fill_axis)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/generic.py", line 8514, in _align_series
	fdata = fdata.reindex_indexer(join_index, lidx, axis=1)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 1224, in reindex_indexer
	self.axes[axis]._can_reindex(indexer)
File "/opt/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3087, in _can_reindex
	raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

************************************************************************************************************************
*****                          Something went wrong with binning with CONCOCT. Exiting...                          *****
************************************************************************************************************************
```

**Comment by ursky** [comment]
Hmm this likely has something to do with your data. I don't think this is not a metawrap issue though - I would make a error report directly at https://github.com/BinPro/CONCOCT. Good luck!
