### ISSUE TITLE
Error in bin refinement module

### ISSUE THREAD

**Issue by palomo11** [bxlab/metaWRAP#34]
Hi,

sorry for late reply in the previous issue, I was on holidays.

Now concoct seems to work fine, however there is a problem when doing the bin refinement.

This is what I get in the bin_refinement folder:

1644 Jun 27 20:03 binsA
6470 Jun 27 20:03 binsB
3418 Jun 27 20:03 binsC
7124 Jun 27 21:04 binsAB
4340 Jun 27 21:04 binsABC
5588 Jun 27 21:04 binsAC
5396 Jun 27 21:04 binsBC
0 Jun 27 21:04 binsA.tmp

And here the error:
```
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/metawrap-env/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/defaultValues.py", line 26, in <module>
    class DefaultValues():
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/defaultValues.py", line 29, in DefaultValues
    __DBM = DBManager()
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 114, in __init__
    if not self.setRoot():
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 177, in setRoot
    path = self.confirmPath(path=path)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 199, in confirmPath
    path = raw_input("Where should CheckM store it's data?\n" \
EOFError: EOF when reading a line
```

```
########################################################################################################################
#####                                      RUNNING CHECKM ON ALL SETS OF BINS                                      #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying: 

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************
```

I guess I did not update the CheckM database...

**Comment by ursky** [comment]
Yes, unfortunately you have to re-configure everything if you reinstall metawrap...
