### ISSUE TITLE
Something went wrong with binning with CONCOCT

### ISSUE THREAD

**Issue by dangchenyuan** [bxlab/metaWRAP#341]
I used the manual method (without conda environment) to install the metawrap. when I was running the concoct binning method, there was this error information as blow:

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                                       indexing .bam alignment files...                                       -----
------------------------------------------------------------------------------------------------------------------------

INITIAL_BINNING/work_files/ALL_READS.bam

------------------------------------------------------------------------------------------------------------------------
-----                             cutting up contigs into 10kb fragments for CONCOCT...                            -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                    estimating contig fragment coverage...                                    -----
------------------------------------------------------------------------------------------------------------------------

/softwares/miniconda2/bin/concoct_coverage_table.py:48: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  df = pd.read_table(fh, header=None)
Traceback (most recent call last):
  File "/softwares/miniconda2/bin/concoct", line 6, in <module>
    import vbgmm
  File "__init__.pxd", line 918, in init vbgmm
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

------------------------------------------------------------------------------------------------------------------------
-----           Looks like our environment has a faulty libgslcblas.so link. Will try to manually create           -----
-----                                         symlink in conda environment                                         -----
------------------------------------------------------------------------------------------------------------------------

conda path: /softwares/miniconda2
Creating symlink /softwares/miniconda2/lib/libgslcblas.so.0 from /softwares/miniconda2/lib/libgslcblas.so

------------------------------------------------------------------------------------------------------------------------
-----                                       Starting binning with CONCOCT...                                       -----
------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/softwares/miniconda2/bin/concoct", line 6, in <module>
    import vbgmm
  File "__init__.pxd", line 918, in init vbgmm
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

************************************************************************************************************************
*****                          Something went wrong with binning with CONCOCT. Exiting...                          *****
************************************************************************************************************************

**Comment by ursky** [comment]
Something strange about your python env. I havent seen this error personally, but i would start my making sure that the conda python and pythonlib are in run priority (set $PATH and $PYTHONPATH).
