### ISSUE TITLE
issue running bin reassembly 

### ISSUE THREAD

**Issue by palomo11** [bxlab/metaWRAP#35]
Hi, 

I'm running bin reassembly in several bins. I have tried with several reads as an input but I always get the same no output.

I have done a test with a set of bins that were improved using bin reassembly (with a previous metWRAP version) but I also get no output.

Output with previous version:
```
     108 Apr  5 21:58 original_bins
     130 Apr  5 23:48 reassembled_bins
     216 Apr  5 23:48 work_files
      75 Apr  5 23:55 reassembled_bins.checkm
     262 Apr  5 23:57 reassembled_bins.stats
  106615 Apr  5 23:57 reassembled_bins.png
     260 Apr  5 23:57 original_bins.stats
   44246 Apr  5 23:57 reassembly_results.eps
 1036345 Apr  5 23:57 reassembly_results.png
```

New output:
```
108 Jul  1 16:40 original_bins
193 Jul  1 16:40 binned_assembly
656 Jul  1 16:40 reads_for_reassembly
560 Jul  1 16:57 reassemblies
  0 Jul  1 16:58 reassembled_bins
```
And the reassemblies folder looks like:
```
 144 Jul  1 16:42 bin.10.permissive
   0 Jul  1 16:43 bin.10.permissive.tmp
 144 Jul  1 16:43 bin.10.strict
   0 Jul  1 16:47 bin.10.strict.tmp
 244 Jul  1 16:51 bin.20.permissive
   0 Jul  1 16:51 bin.20.permissive.tmp
 244 Jul  1 16:55 bin.20.strict
   0 Jul  1 16:55 bin.20.strict.tmp
 274 Jul  1 16:56 bin.52.permissive
   0 Jul  1 16:56 bin.52.permissive.tmp
 274 Jul  1 16:56 bin.52.strict
   0 Jul  1 16:56 bin.52.strict.tmp
 274 Jul  1 16:57 bin.64.permissive
   0 Jul  1 16:57 bin.64.permissive.tmp
 274 Jul  1 16:58 bin.64.strict
   0 Jul  1 16:58 bin.64.strict.tmp

```

Here I upload the log file. It seems it might be related with SPAdes?

[metaWRAP_bin_reassembly.log](https://github.com/bxlab/metaWRAP/files/2152912/metaWRAP_bin_reassembly.log)

**Comment by ursky** [comment]
It appears that you did not specify the `-m` options for available RAM, so the default was 4GB. Naturally, SPAdes ran out of memory. Ill change the default to 24GB for future users.

**Comment by palomo11** [comment]
Hi,

Thanks! Now that part works but I get an error during the checkm step:

```
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 6 bins with 28 threads:
Process SyncManager-1:
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/metawrap-env/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1244, in parseOptions
    self.tree(options)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 133, in tree
    options.bCalledGenes)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 67, in find
    binIdToModels = mp.Manager().dict()
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError
```

**Comment by ursky** [comment]
Honestly, not sure whats going on there. Googling it suggests that it is a system-specific error that could result from a variety of issues. This stems from the CheckM run, not metaWRAP. I wonder what happens if you run CheckM manually the exact same way that metawrap calls it? 

Just from the name of the error, I wonder if you being so deep into directory paths (`/home/projects/env_10000/people/alpal/Microdiversity/samples/BNR_Kartic_merged/binning_concoct/bin_refinement/metaWRAP_bins/reassemble`) is what is causing it. Seems stupid, but worth trying maybe?

By the way, as long as you use the same output dir, you shouldn't have to re-run the entire pipeline to check - metawrap *should* identify that you already got that far.

**Comment by palomo11** [comment]
Hi!

Yes, by shortening the directory path it worked. 

Thanks!

**Comment by chienchi** [comment]
When run checkm (bin_refinement.sh and reassemble_bins.sh) use short path for --tmpdir parameter may solve this issue.  
or don't use --tmpdir but set environment variable TMPDIR=/tmp also works for me.
