### ISSUE TITLE
How to resolve      There are 0 'good' bins found in binsA! ?

### ISSUE THREAD

**Issue by mathavanpu** [bxlab/metaWRAP#421]
Hello,
I am running the metro wrap pipeline, In the bin refinement step I got the error mentioned below, kindly help me to solve it 

**-----               There are 0 'good' bins found in binsA! (>50% completion and <10% contamination)               -----**

metawrap bin_refinement -o BIN_REFINEMENT -t 96 -A INITIAL_BINNING/metabat2_bins/ -B INITIAL_BINNING/maxbin2_bins/ -C INITIAL_BINNING/concoct_bins/ -c 50 -x 10

------------------------------------------------------------------------------------------------------------------------
-----            There is 40 RAM and 96 threads available, and each pplacer thread uses >40GB, so I will           -----
-----                                          use 1 threads for pplacer                                           -----
------------------------------------------------------------------------------------------------------------------------

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                              setting up output folder and copything over bins...                             -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                           there are 5 bins in binsA                                          -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                          there are 10 bins in binsB                                          -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                          there are 18 bins in binsC                                          -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                             There are 3 bin sets!                                            -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                              Fix contig naming by removing special characters...                             -----
------------------------------------------------------------------------------------------------------------------------

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----              There are three bin folders, so there 4 ways we can refine the bins (A+B, B+C, A+C,             -----
-----                                    A+B+C). Will try all four in parallel!                                    -----
------------------------------------------------------------------------------------------------------------------------

Specified 2 input bin sets: -1 binsC -2 binsB
Specified 3 input bin sets: -1 binsA -2 binsB -3 binsC
Specified 2 input bin sets: -1 binsA -2 binsB
Specified 2 input bin sets: -1 binsA -2 binsC
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsC bins
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsA bins
Add folder/bin name to contig name for binsB bins
Add folder/bin name to contig name for binsB bins
Add folder/bin name to contig name for binsC bins
Add folder/bin name to contig name for binsB bins
Add folder/bin name to contig name for binsC bins
Combine all bins together
Combine all bins together
Combine all bins together
The number of refined bins: 8
Combine all bins together
The number of refined bins: 8
The number of refined bins: 5
Exporting refined bins...
Exporting refined bins...
Exporting refined bins...
The number of refined bins: 8
Exporting refined bins...
Extracting refined bin: Refined_5.fasta
Deleting temporary files
Extracting refined bin: Refined_8.fasta
Deleting temporary files
Extracting refined bin: Refined_8.fasta
Deleting temporary files

All done!

All done!

All done!
Extracting refined bin: Refined_8.fasta
Deleting temporary files

All done!

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 8 refined bins in binsAB                                      -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 8 refined bins in binsBC                                      -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 5 refined bins in binsAC                                      -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 8 refined bins in binsABC                                     -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                     Bin refinement finished successfully!                                    -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                            fixing bin naming to .fa convention for consistancy...                            -----
------------------------------------------------------------------------------------------------------------------------

########################################################################################################################
########################################################################################################################

------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 5 bins with 96 threads:
    Finished processing 5 of 5 (100.00%) bins.
Traceback (most recent call last):
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-RDJNFU/.nfs00000000315c43c8001d0958'
  Saving HMM info to file.

  Calculating genome statistics for 5 bins with 96 threads:
    Finished processing 5 of 5 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 5 of 5 (100.00%) bins.
  Extracting 43 HMMs with 96 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 96 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 5 bins into the genome tree with pplacer (be patient).

  { Current stage: 0:05:24.184 || Total: 0:05:24.184 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 5 of 5 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 5 of 5 (100.00%) bins (current: bin.1).      

  Marker set written to: binsA.checkm/lineage.ms

  { Current stage: 0:00:03.744 || Total: 0:05:27.929 }

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 5 bins with 96 threads:
    Finished processing 5 of 5 (100.00%) bins.
Traceback (most recent call last):
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-I2JuJq/.nfs00000000315c4492001d095e'
  Saving HMM info to file.

  { Current stage: 0:01:52.185 || Total: 0:07:20.114 }

  Parsing HMM hits to marker genes:
    Finished parsing hits for 5 of 5 (100.00%) bins.
  Aligning marker genes with multiple hits in a single bin:
    Finished processing 5 of 5 (100.00%) bins.

  { Current stage: 0:00:23.708 || Total: 0:07:43.822 }

  Calculating genome statistics for 5 bins with 96 threads:
    Finished processing 5 of 5 (100.00%) bins.

  { Current stage: 0:00:06.442 || Total: 0:07:50.265 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 5 of 5 (100.00%) bins.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin Id                Marker lineage         # genomes   # markers   # marker sets   0    1    2    3    4    5+   Completeness   Contamination   Strain heterogeneity  
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  bin.unbinned       k__Bacteria (UID203)         5449        104            58        19   21   28   12   15   9       73.85           91.49              16.84          
  bin.1          p__Actinobacteria (UID1454)      732         199           116        86   85   27   1    0    0       62.01           19.45              33.33          
  bin.2              k__Bacteria (UID203)         5449        104            58        84   13   7    0    0    0       11.90            2.66              42.86          
  bin.3                  root (UID1)              5656         56            24        55   1    0    0    0    0        4.17            0.00               0.00          
  bin.4                  root (UID1)              5656         56            24        56   0    0    0    0    0        0.00            0.00               0.00          
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  { Current stage: 0:00:05.052 || Total: 0:07:55.317 }

------------------------------------------------------------------------------------------------------------------------
-----               There are 0 'good' bins found in binsA! (>50% completion and <10% contamination)               -----
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsAB bins                                        -----
------------------------------------------------------------------------------------------------------------------------

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 8 bins with 96 threads:
    Finished processing 8 of 8 (100.00%) bins.
Traceback (most recent call last):
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/apps_940/miniconda/envs/metawrap_prokka/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsAB.tmp/pymp-Jh1tkP/.nfs00000000315c4649001d0967'
  Saving HMM info to file.

  Calculating genome statistics for 8 bins with 96 threads:
    Finished processing 8 of 8 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 8 of 8 (100.00%) bins.
  Extracting 43 HMMs with 96 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 96 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.

**Comment by galodavid** [comment]
I am having the same issue can you please provide any guidance or a solution if you have it
