### ISSUE TITLE
metawrap_bin_refinement.err

### ISSUE THREAD

**Issue by B-1991-ing** [bxlab/metaWRAP#435]
Dear metaWRAP support team,

I have run the command line below several times, but I always got errors in the error file like below:

**Command line**
metawrap bin_refinement -o ./Previous_pipeline/assembly/binning/bin_refinement_ABC -A ./Previous_pipeline/assembly/binning/metabat2_bins -B ./Previous_pipeline/assembly/binning/maxbin2_bins -C ./Previous_pipeline/assembly/binning/concoct_bins -t 40 -c 50

**Error:**
Traceback (most recent call last):
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsO.tmp/pymp-oLJAw5/.nfs00000006e282935d000035bc'
  Saving HMM info to file.

**Error file**
[metawrap_bin_refinement.txt](https://github.com/bxlab/metaWRAP/files/8505839/metawrap_bin_refinement.txt)

Could you help me check what happened there?

I think just because something wrong here in the bin refinement step, I can't get exact binning_results.png with my colleague. Below is the bin_results.png from me and my colleague.

**Bin_results.png (from my colleague and me, with exact same metagenome data sample)**

![binning_results_colleague](https://user-images.githubusercontent.com/54441633/163813704-9dfb977e-37d5-4633-9bee-efca7d047dc3.png)

![binning_results_me](https://user-images.githubusercontent.com/54441633/163813739-18dc31f1-53c0-4013-87e2-1cd35502eae6.png)

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear metaWRAP support team,

**Updated**

I though it might because the memory was run out, so I applied fat node mode (qsub -W group_list=XXX -A XXX -l nodes=2:ppn=40:fatnode,mem=2000gb,walltime=6:00:00 ./scripts/XXX.sh) to run the [metaWRAP](https://github.com/bxlab/metaWRAP) bin refinement step again, but still same error generated in my error file.

  Identifying marker genes in 69 bins with 56 threads:
    Finished processing 69 of 69 (100.00%) bins.
Traceback (most recent call last):
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/services/tools/metawrap-mg/1.3.2/lib/python2.7/shutil.py", line 264, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: 'binsO.tmp/pymp-7O7hil/.nfs00000006f7527fc9000007bc'

Could you help us to figure out what happened there? If this doesn't influence our bin refinement results, I will ignore and go to further step.

Best,

Bing

**Comment by ursky** [comment]
Hi Bing, thanks for the detailed report. Looks like CheckM is causing some sort of memory/subprocess leak that is causing some of the gene family HMMs from being properly identified, which in turn causes CheckM to underestimate the completion and contamination values of some of the bins. This appears to be a rare artifact so I suspect your final output bins are likely quite similar to those from your colleague, but the CheckM values are not accurate. What I would do is re-run CheckM manually by yourself (thus avoiding the parallel memory leak bug). You should see the values go up to the expected values.

**Comment by B-1991-ing** [comment]
Hi Ursky,

Thank you very much for your reply and confirmation. I'll run the CheckM manually later to check if it is exactly same.

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear metaWRAP support team,

Is there anyway that I can do to avoid **the error message (OSError: [Errno 16] Device or resource busy: 'binsO.tmp/pymp-7O7hil/.nfs00000006f7527fc9000007bc')** appear in my error file?

I tried to load **checkm-genome/1.1.11** in the anocaonda environment **anaconda3/2021.11**, but same error. 

It required 56 threads, then I tried to apply 56 ppn(or threads) on our HPC cluster, but for each fat node (in fat nodes, we can use more memory), then applied 40 ppn for one node(or threads), ended with same error. 

Then, I tried to apply 2 nodes with 28 ppn each node has. But, also not working.

Also, I tried newest versions of metawrap, finally ended same error.

Best,

Bing
