### ISSUE TITLE
help! OSError: [Errno 16] Device or resource busy: '

### ISSUE THREAD

**Issue by xianglongwei** [bxlab/metaWRAP#473]
**execute this command：**

metawrap bin_refinement -o bin_refinement/s1 -t 64 -A based-megahit/s1/metabat2_bins/ -B based-megahit/s1/maxbin2_bins/ -C based-megahit/s1/concoct_bins/ -c 50 -x 10

**The following error occurs, but it seems that the program can continue：**

Traceback (most recent call last):
  File "/NAS/home/chenyx/micromamba/envs/metawrap/lib/python2.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/NAS/home/chenyx/micromamba/envs/metawrap/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/NAS/home/chenyx/micromamba/envs/metawrap/lib/python2.7/shutil.py", line 275, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/NAS/home/chenyx/micromamba/envs/metawrap/lib/python2.7/shutil.py", line 273, in rmtree
    os.remove(fullname)
**OSError: [Errno 16] Device or resource busy: 'binsA.tmp/pymp-o9o3Za/.nfs000000018c36fa3e000b0d86'**

I don't know how to fix this, please help, thanks！

**Comment by xianglongwei** [comment]
Does it affect the result of the execution?

**Comment by weishwu** [comment]
I'm also getting this error. It was reported in another post and @ursky recommended running checkM manually. @ursky Is there any parameter setting we can change in one of the metawrap package files to avoid this error? If we manually run checkM outside metawrap, how do we connect the results with metawrap?
