### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'label'

### ISSUE THREAD

**Issue by xuechunxu** [bxlab/metaWRAP#58]
Hi, I got an error when trying to Re-assemble the consolidated bin set with the Reassemble_bins module. Here is the log:

>  *******************************************************************************
>  [CheckM - lineage_set] Inferring lineage-specific marker sets.
> *******************************************************************************
> 
>   Reading HMM info from file.
>   Parsing HMM hits to marker genes:
>     Finished parsing hits for 294 of 294 (100.00%) bins.
> 
>   Determining marker sets for each genome bin.
>     Finished processing 9 of 294 (3.06%) bins (current: bin.52.strict).    
> Unexpected error: <type 'exceptions.AttributeError'>
> Traceback (most recent call last):
>   File "/home/xuechunxu/miniconda2/envs/metawrap-env/bin/checkm", line 712, in <module>
>     checkmParser.parseOptions(args)
>   File "/home/xuechunxu/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1245, in parseOptions
>     self.lineageSet(options)
>   File "/home/xuechunxu/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 230, in lineageSet
>     resultsParser, options.unique, options.multi)
>   File "/home/xuechunxu/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/treeParser.py", line 515, in getBinMarkerSets
>     domainNode = self.__findDomainNode(node)
>   File "/home/xuechunxu/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/treeParser.py", line 244, in __findDomainNode
>     if curNode.label:
> AttributeError: 'NoneType' object has no attribute 'label'
> 
> ************************************************************************************************************************
> *****                             Something went wrong with running CheckM. Exiting...                             *****
> ************************************************************************************************************************

**Comment by ursky** [comment]
Thanks for the feedback, and sorry for the late response. Were you able to get this working? It looks to be an issue with the older versions of CheckM that metaWRAP uses: https://github.com/Ecogenomics/CheckM/issues/117. We can hopefully resolve this by updating CheckM to a newer version, but first I need to make metaWRAP accept this new verison. I updated the metaWRAP dependency in `metaWRAP v=1.03`. Please update to `metawrap-mg=1.03`, and then update to `checkm-genome=1.0.12`. Let me know what happens.
