### ISSUE TITLE
path issue with concoct 

### ISSUE THREAD

**Issue by karoraw1** [bxlab/metaWRAP#7]
Similar issue to the previous one, this time on line 282. 

Yields the following:
```
Traceback (most recent call last):
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.4.0', 'concoct')
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/scratch/users/karoraw1@jhu.edu/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 76, in <module>
    results = main(args)
  File "/scratch/users/karoraw1@jhu.edu/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 20, in main
    composition, cov, cov_range = load_data(args)
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 16, in load_data
    args.length_threshold
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 70, in load_composition
    kmer_len
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 40, in _calculate_composition
    for seq in SeqIO.parse(comp_file,"fasta"):
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 581, in parse
    with as_handle(handle, mode) as fp:
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home-3/karoraw1@jhu.edu/scratch/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/Bio/File.py", line 88, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: '/home-3/karoraw1@jhu.edu/scratch/THRASH_LIBS/Scripts//home-3/karoraw1@jhu.edu/scratch/THRASH_LIBS/DNA_BINS/work_files/assembly.fa'
```

**Comment by ursky** [comment]
Great catch! The issue has been fixed in metaWRAP v=0.7.2 
Thank you for the feedback!
