### ISSUE TITLE
Error settig CheckM

### ISSUE THREAD

**Issue by palomo11** [bxlab/metaWRAP#90]
Hi,

I recently installed the version 1.0.5. I have run bin refinement but there was an error because CheckM was not found. I have tried to set CheckM but it called for this error:

```
(metawrap-env) $ checkm data setRoot
It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying: 
/home/projects/env_10000/people/alpal/databases/CheckM_database/

Path [/home/projects/env_10000/people/alpal/databases/CheckM_database] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/metawrap-env/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 32, in <module>
    from checkm.treeParser import TreeParser
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/treeParser.py", line 27, in <module>
    import dendropy
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/DendroPy-4.2.0-py2.7.egg/dendropy/__init__.py", line 24, in <module>
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/DendroPy-4.2.0-py2.7.egg/dendropy/dataio/__init__.py", line 20, in <module>
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/DendroPy-4.2.0-py2.7.egg/dendropy/dataio/newickreader.py", line 27, in <module>
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/DendroPy-4.2.0-py2.7.egg/dendropy/utility/textprocessing.py", line 40, in <module>
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

I have completely deleted metawrap and install again (now the v. 1.0.6) from scratch but when I try to set CheckM I still get a similar error:

```
(metawrap-env) $ checkm data setRoot
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/metawrap-env/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 49, in <module>
    from checkm.plot.gcPlots import GcPlots
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/plot/gcPlots.py", line 24, in <module>
    from AbstractPlot import AbstractPlot
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/checkm/plot/AbstractPlot.py", line 22, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/home/people/alpal/.conda/envs/metawrap-env/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

Any idea?

**Comment by ursky** [comment]
The issue is coming from CheckM itself, not from metaWRAP. So focus on fixing that first before attempting the pipeline.  It looks like there is an issue with your operating system's default encoding, which conflicts with what is expected by the miniconda's python. It looks like a common issue, which you can probably fix by re-setting the defaults in your `~/.bash_profile`. See issues: https://github.com/explosion/spaCy/issues/1684, https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7, and others from google. I never dealt with the issue, so I don't have exact advice.

**Comment by ursky** [comment]
On a side note, I am not sure why you're encountering this issue only now. You've used the software from the start. I suspect this is because I updated metaWRAP to use the latest and greatest version of CheckM, which might use different packages. This is cheating a bit, but you could try to downgrade to `checkm-genome=1.0.7` to see if that fixes it.

**Comment by palomo11** [comment]
Thanks for the advice.

I have done what it is suggested in one of the links you sent me. It seems now the CheckM database is set fine. I'm running bin refinement. I will let you know if there is any error.
