### ISSUE TITLE
Running CheckM error

### ISSUE THREAD

**Issue by jjjscuedu** [bxlab/metaWRAP#92]
Dear all,

When I try to run bin_refinement on test data like this:

metawrap bin_refinement -o BIN_REFINEMENT -t 96 -A INITIAL_BINNING/metabat2_bins/ -B INITIAL_BINNING/maxbin2_bins/ -c 50 -x 10

However, there are something error like this:

------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/gpfs02/home/jingjing/miniconda2/envs/metawrap-env/bin/checkm", line 36, in <module>
    from checkm import main
  File "/gpfs02/home/jingjing/miniconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 23, in <module>
    import numpy as np
  File "/gpfs02/home/jingjing/compile_software/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/gpfs02/home/jingjing/compile_software/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/gpfs02/home/jingjing/compile_software/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/gpfs02/home/jingjing/compile_software/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/gpfs02/home/jingjing/compile_software/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /gpfs02/home/jingjing/compile_software/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_FromObject

I am not sure the reason for this?

In fact, I have installed numpy by : pip install numpy.

Can anyone give me some suggestions?

Jingjing

**Comment by ursky** [comment]
Its possible that pip is installing a different version of numpy. I would uninstall pip's numpy, and install it through conda directly - I believe metaWRAP already has that as a requirement.

**Comment by ursky** [comment]
On a side note, I would make sure you can run CheckM first, before re-attempting running metaWRAP.
