### ISSUE TITLE
checkm error during bin refinement

### ISSUE THREAD

**Issue by chloelulu** [bxlab/metaWRAP#97]
Hi, 
I got the following errors during `metawrap bin_refinement`.

> ------------------------------------------------------------------------------------------------------------------------
> -----                                     Bin refinement finished successfully!                                    -----
> ------------------------------------------------------------------------------------------------------------------------
> 
> 
> ------------------------------------------------------------------------------------------------------------------------
> -----                            fixing bin naming to .fa convention for consistancy...                            -----
> ------------------------------------------------------------------------------------------------------------------------
> 
> 
> ########################################################################################################################
> #####                                      RUNNING CHECKM ON ALL SETS OF BINS                                      #####
> ########################################################################################################################
> 
> 
> ------------------------------------------------------------------------------------------------------------------------
> -----                                         Running CheckM on binsA bins                                         -----
> ------------------------------------------------------------------------------------------------------------------------
> 
> It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
> Where should CheckM store it's data?
> Please specify a location or type 'abort' to stop trying:
> Traceback (most recent call last):
>   File "/home/zzhang78/miniconda2/bin/checkm", line 36, in <module>
>     from checkm import main
>   File "/home/zzhang78/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 25, in <module>
>     from checkm.defaultValues import DefaultValues
>   File "/home/zzhang78/miniconda2/lib/python2.7/site-packages/checkm/defaultValues.py", line 26, in <module>
>     class DefaultValues():
>   File "/home/zzhang78/miniconda2/lib/python2.7/site-packages/checkm/defaultValues.py", line 29, in DefaultValues
>     __DBM = DBManager()
>   File "/home/zzhang78/miniconda2/lib/python2.7/site-packages/checkm/checkmData.py", line 114, in __init__
>     if not self.setRoot():
>   File "/home/zzhang78/miniconda2/lib/python2.7/site-packages/checkm/checkmData.py", line 140, in setRoot
>     path = self.confirmPath(path=path)
>   File "/home/zzhang78/miniconda2/lib/python2.7/site-packages/checkm/checkmData.py", line 162, in confirmPath
>     path = raw_input("Where should CheckM store it's data?\n" \
> IOError: [Errno 9] Bad file descriptor
> 
> ************************************************************************************************************************
> *****                             Something went wrong with running CheckM. Exiting...                             *****
> ************************************************************************************************************************
> 
> 
> real    396m29.000s
> user    1044m46.816s
> sys     28m10.116s

I am not sure where cause the error. It seems that bin refinement has been finished, while checkm running has some problem. my metawrap is v1.1.
May I please have the help?

Thanks.

**Comment by ursky** [comment]
Looks like you never installed the CheckM database. See metaWRAP installation instructions.

**Comment by chloelulu** [comment]
Hi， @ursky ，

Thanks. I think I have downloaded the database as shown in the figure.
![image](https://user-images.githubusercontent.com/28763565/51362193-99447200-1aa0-11e9-9996-0517e76fca8e.png)
But I did not `checkm data setRoot`. Just now I make the setRoot to this directory. It resulted to 
```
Path [/home/zzhang78/metawrap_database/MY_CHECKM_FOLDER] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).
Data location successfully changed to: /home/zzhang78/metawrap_database/MY_CHECKM_FOLDER
```

Now I type `checkm -h`, this function works now. Does that mean it is ok now? Or any other method can check the database is set up successfully? Since bin_refinement takes time, and I just want to make sure if checkm -h is ok, and it is ok to run. 
Thanks so much.

**Comment by ursky** [comment]
It should be OK

**Comment by chloelulu** [comment]
@ursky  Great! Thanks! Finger crossed to the results!
